sillsdev/Glyssen

- Glyssen/Controls/ScriptBlocksViewer.Designer.cs
- Glyssen/Controls/ScriptBlocksViewer.cs
When the mouseover event is triggered, up to ten parents are checked above the target to see if the element is a context.
Tooltip is only shown when no tooltip is present.
Tooltip is only hidden when an area that isn't a context is entered.
> PG-253 Tooltip now shows on hover over any part of context

- Glyssen/Controls/VoiceActorInformationGrid.Designer.cs
- Glyssen/Controls/VoiceActorInformationGrid.cs
- Glyssen/Dialogs/VoiceActorAssignmentDlg.Designer.cs
- Glyssen/Dialogs/VoiceActorAssignmentDlg.cs
- Glyssen/Dialogs/VoiceActorInformationDlg.Designer.cs
VA Info's EditMode is now EditOnEnter, which makes it easier to edit. However, the grid is readonly in VA Assign unless the "Edit" button has been clicked, whereupon the grid is editable until left.
Other un-related minor adjustments:
- Widths of split panel 2, VA Info columns, and SaveStatuses (Todo: autosize seems broken here) adjusted
- Initial color of VA Info SaveStatus white
- Initial call to AlignBtnAssignActorToSplitter in VA Assign
> PG-303 Improve VA Info editing with Edit button

- DevTools/TermTranslator/Processor.cs
- DistFiles/localization/Glyssen.en.tmx
- DistFiles/localization/Glyssen.es.tmx
- DistFiles/localization/Glyssen.fr.tmx
- DistFiles/localization/Glyssen.pt.tmx
- DistFiles/localization/Glyssen.zh-hans.tmx
- DistFiles/localization/Glyssen.zh-hant.tmx
- Glyssen/Resources/CharacterDetail.txt
- Glyssen/Resources/CharacterVerse.txt
This now works correctly for processing proper names with explanatory text following a comma. It also prevents attempting of word-for-word translation of terms that do not begin with a proper name. Did a bunch of cleanup to localization files related to the latter issue. Also, now a few of the translations for French and Portuguese are human-edited (with a lot of help from Google translate and my *limited* knowledge o.those languages).
> Tom's updates to character id localizations and automated processor

- Glyssen/Dialogs/VoiceActorAssignmentViewModel.cs
VoiceActorAssignmentViewModel.GetMultiColumnActorDataTable now returns DataTables that do not include CameoActors unless the supplied group is null or is assigned a cameo actor
> Removed Cameo Actors from selection dropdown in VoiceActorAssignmentDlg.

- Glyssen/Controls/VoiceActorInformationViewModel.cs
- Glyssen/Dialogs/VoiceActorAssignmentDlg.cs
- Glyssen/Dialogs/VoiceActorInformationDlg.Designer.cs
- Glyssen/Dialogs/VoiceActorInformationDlg.cs
Ignore header row in m_characterGroupGrid_CellContentClick
Fix sorting direction icon in headers
Allow user to click `OK` after deleting the last actor
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/71)
> Fix some problems with m_characterGroupGrid

- Glyssen/Project.cs
- GlyssenTests/ProjectTests.cs
If there is only one book in the bundle, don't make the user select it before continuing.
Resolves #PG-386
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/75)
> Issue PG-386: don't make the user select the only book

- Glyssen/Dialogs/BlockNavigatorViewModel.cs
- Glyssen/Dialogs/QuotationMarksDlg.Designer.cs
- Glyssen/Dialogs/QuotationMarksDlg.cs
- Glyssen/Dialogs/QuotationMarksDlg.resx
- Glyssen/Quote/QuoteParser.cs
- GlyssenTests/Quote/QuoteParserTests.cs
- GlyssenTests/TestProject.cs
Changed QuoteParser so changes can be tested can be run without updating the project.
Changed BlockNavigatorViewModel so it can show blocks that are not part of a project (output from the Quoteparser changes).
Resolves #PG-544
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/76)
> Issue PG-544: Don't show test results until until quote parser runs

- Glyssen/Dialogs/QuotationMarksDlg.cs
Need to lock down the UI while quote parsing is happening in the Quote Settings dialog.
Resolves #PG-545
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/77)
> Issue PG-545: Disable UI while quote parsing

- Glyssen/Dialogs/OpenProjectDlg.Designer.cs
- Glyssen/Dialogs/OpenProjectDlg.cs
Wait until the user changes something before saving the grid settings.
Have the columns still automatically fill the width of the grid while allowing the user to change the columns widths.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/79)
> Issue PG-201: In Open Project dialog, improve column width behavior

- Glyssen/Controls/VoiceActorInformationGrid.Designer.cs
- Glyssen/Controls/VoiceActorInformationGrid.cs
UI strings in Voice Actor Information drop-down combos do not update if localized strings are changed.
Resolves #PG-478
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/82)
> PG-478: Update voice actor info dropdowns when UI language changes

- Glyssen/App.config
- Glyssen/Properties/Settings.Designer.cs
- Glyssen/Properties/Settings.settings
- Glyssen/UsxParser.cs
- GlyssenTests/UsxParserTests.cs
Properly handle extraneous whitespace between char and note elements (PG-593)
Ignore a verse with no text (PG-594)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/87)
> Fix two edge cases in UsxParser (PG-593 & PG-594)

- build/Glyssen.proj
I've fixed the known_hosts on the build agent, and also fixed the reg-ex on software.sil.org.  With these changes it should er just work.  If it doesn't I can followup on the dev box and make sure it works.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/90)
> Fixed rsync args for upload to software.sil.org

- build/Glyssen.proj
- Ensure that the server web user can read the file.
- Change the style of the key path to cygwin style to reduce
warnings in the output.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/95)
> Fix Upload: Permissions for other and cygwin style path

- Glyssen/Quote/QuoteParser.cs
- GlyssenTests/Quote/QuoteParserTests.cs
If the only dialog marker is a colon, `m_regexStartsWithFirstLevelOpener` is not set, resulting in an "Object reference not set" exception.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/105)
> PG-636: "Object reference not set" in QuoteParser

- Glyssen/Controls/VoiceActorInformationGrid.cs
CellEndEdit is being called with a RowIndex that is no longer valid.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/109)
> PG-639: Out of range exception when adding actor is canceled

- Glyssen/Project.cs
The project ControlFileVersion was being reset to 0, which triggered a re-parsing of the entire text.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/112)
> PG-612: renaming text bundle erases character assignments

- Glyssen/Controls/VoiceActorInformationGrid.cs
If RowIndex >= RowCountLessNewRow, this always indicates the current row was deleted.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/114)
> PG-639.2: Need to ignore IsDirty

- Glyssen/Controls/CastSizePlanningOptions.cs
- Glyssen/Dialogs/CastSizePlanningDlg.cs
- Glyssen/Dialogs/CastSizePlanningViewModel.cs
- Glyssen/Dialogs/VoiceActorInformationDlg.Designer.cs
- Glyssen/Dialogs/VoiceActorInformationDlg.cs
Set the "Match Voice Actor List" option automatically only when the Voice Actor List dialog was displayed automatically, not after it was displayed because the user clicked the link which has instructions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/116)
> Update how Voice Actor List option is set

- Glyssen/BlockSplitData.cs
- GlyssenTests/Dialogs/AssignCharacterViewModelTests.cs
If a split is placed between blocks of a multi-block quote, VerseToSplit will be null. The comparer was trying to convert this to an int which was the cause of the crash.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/134)
> PG-671: crash when multi-splitting

- Glyssen/Dialogs/VoiceActorAssignmentDlg.cs
Prevent "DataGridViewComboBoxCell value is not valid" message when user types the name of a cameo actor into the voice actor assignment grid
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/147)
> Fix false invalid value error message

- Glyssen/Dialogs/AssignCharacterViewModel.cs
- GlyssenTests/Dialogs/AssignCharacterViewModelTests.cs
- GlyssenTests/Rules/CharacterGroupGeneratorTests.cs
Narrator will always be at the top of the list (key 1) and Jesus, if he speaks, will be second (key 2).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/153)
> PG-528: Fixed Keyboard Shortcut for Jesus and Narrator

- Glyssen/BookScript.cs
- Glyssen/ReferenceText.cs
- GlyssenTests/ReferenceTextTests.cs
Bug caused it to crash because of failure to split verse bridges.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/183)
> PG-734: Fixed logic for splitting vernacular to match the reference text breaks

- DevTools/ReferenceTextUtility.cs
- Glyssen/BookScript.cs
- Glyssen/Bundle/GlyssenDblTextMetadata.cs
- Glyssen/ReferenceText.cs
- GlyssenTests/BookScriptTests.cs
- GlyssenTests/ReferenceTextTests.cs
As part of this, I made some of the previously static methods in ReferenceText into members. This allows proper error reporting (and positions us to deal with PG-699: the need to split blocks in the reference guide to match end-of-verse splits in the vernacular).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/187)
> PG-736: Completed work to handle splitting around verse bridges and sub-verse letters.

- Glyssen/Block.cs
- Glyssen/ProjectDataMigrator.cs
- Glyssen/Resources/CharacterVerse.txt
- GlyssenTests/Character/CharacterAssignerTests.cs
- GlyssenTests/ProjectDataMigratorTests.cs
The symptom was that disambiguation was at 100% but there were still blocks
which needed to be assigned.
Also cleaned up one scenario in which characterId was Unknown or Ambiguous
but characterIdInScript was non-null.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/188)
> Ensure userconfirmed is false when characterId is Unknown or Ambiguous (PG-739)

- Glyssen/ReferenceText.cs
- GlyssenTests/ReferenceTextTests.cs
… to match verse breaks in the Reference Text.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/194)
> PG-743: Prevented failure message when splitting blocks with verse bridges

- Glyssen/ReferenceText.cs
- GlyssenTests/ReferenceTextTests.cs
This condition can legitimately happen if a verse number is missing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/196)
> PG-742: Made "split failed" message only show in DEBUG

- Glyssen/BookScript.cs
- Glyssen/ScrStylesheetAdapter.cs
- GlyssenTests/ReferenceTextTests.cs
If a `poetic` block has the same speaker as the previous block, combine the block with the previous one
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/203)
> PG-741: Prevent extra breaks in vernacular from `poetic` blocks

- Glyssen/BookScript.cs
- Glyssen/Dialogs/AssignCharacterDlg.cs
- Glyssen/Dialogs/AssignCharacterViewModel.cs
- GlyssenTests/BookScriptTests.cs
- GlyssenTests/Dialogs/AssignCharacterViewModelTests.cs
Select the second character when a verse has two expected speakers and two identified quotations and the user assigns the first one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/205)
> PG-525: Automatically disambiguate second character in verse when possible

- Glyssen/BookScript.cs
- Glyssen/Dialogs/AssignCharacterViewModel.cs
- GlyssenTests/BlockTests.cs
- GlyssenTests/BookScriptTests.cs
- GlyssenTests/Resources/TestVersification.txt
When splitting a block and assigning a character, made it mark the block as user confirmed, to prevent inserting a block that appears to have had its character ID set by Glyssen (which messes up the block indices in the navigator). We now also assign the override to use in the script if needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/206)
> PG-526: Mark blocks as user-confirmed when assigning during split

- Glyssen/Block.cs
- Glyssen/BookScript.cs
- GlyssenTests/ReferenceTextTests.cs
This involved major refactoring to move much of the SplitBlock logic into the Block class.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/216)
> PG-761: Added code to split English reference text when primary RT is split

- Glyssen/MainForm.cs
- Glyssen/ProjectExporter.cs
This fix as cherry-picked from master branch (PG-759)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/220)
> PG-767: Crash viewing recording script if UI language not English

- Glyssen/Dialogs/ProjectSettingsDlg.Designer.cs
Fixed layout of controls on various pages of Project Settings dialog …
#	Glyssen/Dialogs/ProjectSettingsDlg.Designer.cs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/236)
> PG-796: merged changes from 0.17 to fix layout of Project Settings dialog

- Glyssen/Controls/ScriptBlocksGridView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/240)
> Fixed crash caused by trying to set the first displayed row index to a value that is out of range.

- Glyssen/Controls/ScriptBlocksGridView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/244)
> Put sanity checks inside SafeInvoke call to prevent crash when row count is changing.

- Glyssen/Block.cs
- Glyssen/PortionScript.cs
This bug was reported in a comment in PG-810. (This fix has already been made in 0.11, but I'm just doing it quick here to get Connie up and running again.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/246)
> Fixed null reference exception during export

- Glyssen/Block.cs
- Glyssen/BlockMatchup.cs
- Glyssen/Character/CharacterVerseData.cs
- Glyssen/Dialogs/AssignCharacterDlg.cs
- Glyssen/Dialogs/AssignCharacterViewModel.cs
- Glyssen/Dialogs/BlockNavigatorViewModel.cs
- Glyssen/ProjectDataMigrator.cs
- GlyssenTests/Dialogs/BlockNavigatorViewModelTests.cs
- GlyssenTests/ProjectDataMigratorTests.cs
PG-805: Prevented problem caused when users apply a rainbow match that doesn't correspond to a character/delivery pair in the control file. Also made it less likely for the user to do this by accident.
PG-820: Fixed crash when clicking Apply when the current block is a non-relevant block in the last rainbow group.
Also fixed data migration bug reported by JimA regarding Ambiguous blocks getting set as user confirmed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/251)
> PG 805 & PG-820, etc.

- build/Glyssen.proj
The organization of the directory used by software.sil.org has changed to have an extra "r" directory.
Adding sudo -u vu2004 to the --rsync-path will cause the uploaded files to be owned by vu2004 which is the same user that would operate FTP. This allows product teams to use a tool like Filezilla to delete old files from time to time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/258)
> Update publish path

- Glyssen/BlockMatchup.cs
version of Glyssen allowed ref block assignment without specifying the character.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/267)
> PG-811: Changed exception to debug assertion for scenario where a previous

- Glyssen/Dialogs/AssignCharacterDlg.cs
- Glyssen/Dialogs/BlockNavigatorViewModel.cs
Also, added wait cursor changing the filter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/280)
> PG-843: Fixed crash and made it so blocks for books that do not have a corresponding reference text are not considered misalignments.

- Glyssen/BlockMatchup.cs
- Glyssen/Dialogs/AssignCharacterViewModel.cs
- Glyssen/Dialogs/BlockNavigatorViewModel.cs
- GlyssenTests/Dialogs/AssignCharacterViewModelTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/283)
> PG-845: Prevent crash when parser changes make previously saved start index (for Identify Speaking Parts) invalid.

- Glyssen/Dialogs/ExportDlg.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/286)
> Fixed crash in UpdateBookDisplay caused by using formatted message instead of directory name

- Glyssen/Dialogs/AssignCharacterDlg.cs
I'm making this change mostly because I got a debug assertion failure (which I can't understand or reproduce) as a result of setting the delivery to normal, and I'm thinking I might at least reduce the likelihood of it happening again by not setting the delivery unless necessary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/290)
> Only try to reset narrator's delivery to normal if it isn't already normal

- Glyssen/Properties/AssemblyInfo.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/295)
> This AssemblyInfo file got missed by accident when upping version to 0.18

- Glyssen/Controls/ScriptBlocksGridView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/314)
> PG-884: Prevent crash by calling ScrollDesiredRowsIntoView asynchronously from OnRowHeightChanged

- Glyssen/Dialogs/QuotationMarksDlg.Designer.cs
- Glyssen/Dialogs/QuotationMarksDlg.cs
- Glyssen/Quote/QuoteParser.cs
PG-880: When user presses Cancel after pressing OK (and then electing…to review quote system), calling dialog still updates UI to reflect saved changes.
PG-885: UX improvements in Quotation Marks dialog
PG-886: Fixed bug that was causing block navigator in Quotation Marks dialog to include all books instead of just Included books
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/315)
> Improvements/fixes in Quotation Marks dialog

- Glyssen/Project.cs
Initializes Status.AssignCharacterMode = BlocksToDisplay.NotAllignedToReferenceText instead of NotYetAssigned.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/346)
> PG-925 Changed Project.ClearAssignCharacterStatus().  

- Glyssen/Dialogs/AssignCharacterDlg.cs
to use DataGridViewCell.MeasureTextHeight() recommended by Tom.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/347)
> PG-897 A different approach to m_dataGridReferenceText_CellEnter() 

- Installer/Installer.wxs
- build/TestInstallerBuild.bat
Pops up notice that it requires 4.6.1 in order to install Glyssen when 4.6 or earlier is installed or .NET Framework is not installed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/349)
> PG-942 Successfully installs Glyssen when .NET Framework 4.6.1 is installed.

- Glyssen/BlockElement.cs
- Glyssen/ProjectExporter.cs
- GlyssenTests/ProjectExportTests.cs
This ended up not having anything to do with PG-955, which was a duplicate of the already-fixed PG-905, but I also added another test for that, and I decided to keep it because it seems to be testing an additional useful case (primary reftext has only a verse number and secondary reftext is an empty string.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/357)
> Prevented crash when empty ScriptText Content is deserialized as a null.

- Glyssen/Block.cs
- Glyssen/BookScript.cs
- Glyssen/ReferenceText.cs
- GlyssenTests/BookScriptTests.cs
- GlyssenTests/ReferenceTextTests.cs
Also included a little fix that was causing an incorrect block break between a leading open bracket and the actual verse number for disputed passages (e.g., MRK 16:9)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/380)
> PG-962: Made single-voice books export nicely, aligned to the reference text.

- Glyssen/Project.cs
- GlyssenTests/Rules/CharacterGroupGeneratorTests.cs
- GlyssenTests/Rules/CharacterGroupsAdjusterTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/381)
> PG-965: Fixed Glyssen to not try to regenerate groups if extra-biblical blocks are omitted

- Glyssen/Dialogs/AssignCharacterDlg.cs
- Glyssen/Dialogs/AssignCharacterViewModel.cs
- GlyssenTests/Dialogs/AssignCharacterViewModelTests.cs
Happened when changing a character to a non-narrator after adding a project-specific delivery.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/382)
> PG-848: Fixed crash (DataGridViewComboBoxCell value is not valid)

- Glyssen/MainForm.cs
during upgrade, parsing, etc. so that if anything goes wrong, Glyssen isn't permanently hamstrung.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/385)
> Added code to clear the CurrentProject setting

- Glyssen/Controls/ScriptBlocksViewer.cs
- Glyssen/MainForm.cs
This was caused by trying to calculate alignment percentage on a project that hasn't yet been parsed)
Also fixed a crash caused by trying to invoke on the UI thread before the ScriptBlocksViewer handle is created.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/388)
> PG-981: Prevented null object reference exception when opening a new project

- Glyssen/Quote/QuoteParser.cs
- GlyssenTests/Quote/QuoteParserTests.cs
Crash was caused by incorrectly using length of previous interruption to get substring of last block element, whose length may be too short.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/389)
> PG-982: Fix logic to prevent crash in BreakOutInterruptionsFromWorkingBlock

- Glyssen/Block.cs
- Glyssen/Quote/QuoteParser.cs
- GlyssenTests/Quote/QuoteParserTests.cs
- GlyssenTests/Resources/TestCharacterVerse.txt
(particularly when using dialogue quotes) that cause cause a crash from trying to split a block at the very beginning.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/395)
> PG-1017: Prevent over-aggressive detection of interruptions

- Glyssen/Block.cs
- Glyssen/Dialogs/SplitBlockDlg.cs
- GlyssenTests/BlockTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/403)
> Fixed splitting problem caused by characters in data that get encoded (e.g., &nbsp;) in HTML.

- Glyssen/BlockNavigator.cs
- Glyssen/Dialogs/AssignCharacterDlg.cs
- Glyssen/Dialogs/BlockNavigatorViewModel.cs
- Glyssen/Glyssen.csproj
- Glyssen/IBlockAccessor.cs
- GlyssenTests/BlockNavigatorTests.cs
- GlyssenTests/Dialogs/BlockNavigatorViewModelTests.cs
Tom and I worked on this together. No code review necessary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/418)
> Fix Split Dialog such that it always loads blocks corresponding to the selected quote

- Glyssen/Dialogs/AssignCharacterViewModel.cs
- Glyssen/Dialogs/BlockNavigatorViewModel.cs
- GlyssenTests/Dialogs/AssignCharacterViewModelTests.cs
Tom and I worked on this together. No review necessary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/419)
> Prevent errant increment of indices when "split" occurs between blocks

- Glyssen/Dialogs/AssignCharacterViewModel.cs
- Glyssen/Dialogs/BlockNavigatorViewModel.cs
- GlyssenTests/Dialogs/AssignCharacterViewModelTests.cs
- GlyssenTests/Dialogs/BlockNavigatorViewModelTests.cs
This is inefficient but better than crashing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/421)
> Ensure valid state after a split by totally resetting state (PG-1075)

- Glyssen/ReferenceText.cs
(used only in debug mode) to prevent needless alerts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/455)
> Minor improvement to BlockContainsVerseEndInMiddleOfVerseBridge

- Glyssen/Dialogs/AssignCharacterDlg.cs
- Glyssen/Resources/CharacterVerse.txt
This is the case of this crash that happens when moving a ref block whose character is not set.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/469)
> PG-1123, PG-1131: Fixed "Sequence contains no matching element"

- Glyssen/BlockMatchup.cs
- Glyssen/ProjectDataMigrator.cs
- Glyssen/Quote/QuoteParser.cs
- Glyssen/Resources/CharacterVerse.txt
- GlyssenTests/BlockTests.cs
- GlyssenTests/Quote/QuoteParserTests.cs
error caused by orphaned start quote block when breaking off an interruption.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/470)
> PG-1160, PG-1097, PG-1120: Fixed "Sequence contains no elements"

- Glyssen/Dialogs/AssignCharacterViewModel.cs
- Glyssen/Resources/CharacterVerse.txt
Also prevent creating a pending blank character for an unassigned block from the split dialog
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/477)
> PG-1166: Fixed off-by-one error, going off the end of a block matchup

- Glyssen/Dialogs/ProjectSettingsDlg.cs
- Glyssen/Dialogs/SelectBundleForProjectDlg.cs
- Glyssen/Dialogs/SelectProjectDlg.cs
- Glyssen/Glyssen.csproj
- Glyssen/Project.cs
…by showing the name of the project in the dialog box title and having the original bundle filename be the default.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/478)
> Improved user experience when they have to try to find a bundle for a Glyssen project 

- Glyssen/Dialogs/AssignCharacterViewModel.cs
- Glyssen/Dialogs/BlockNavigatorViewModel.cs
PG-1166: Error that could allow a blank character ID to go into pending list (and show up as blank entry in combo box)
PG-1090: Removed debug assertion that alerted developer to condition that was though to be impossible. In light of this scenario, made minor correction to logic.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/479)
> PG-1166 & PG-1090: Fixed logic errors

- DistFiles/localization/Glyssen.es.tmx
- Glyssen/Dialogs/UnappliedSplitsDlg.Designer.cs
- Glyssen/MainForm.cs
Made Unapplied Splits dialog lay out dynamically based on the length of the localized strings.
Added Spanish translation for DialogBoxes.UnappliedSplitsDlg.CopyToClipboard
(unrelated) Made last export location invisible if the stored folder path does not exist.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/480)
> PG-1145: Minor I18n and L10n improvements

- Glyssen/MainForm.cs
- Glyssen/Project.cs
- Glyssen/ProjectBase.cs
1) Improved the code that creates a glyssenshare to ensure the zip file includes a copy of the Paratext vrs file.
2) Improved the code that creates a project from a glyssenshare to use the live project's versification file if available, but fall back to the one from the glyssenshare file if not. As a final fallback (for compatibility with old glhyssenshare files), it defaults to English (notifying the user of a possible problem).
3) When removing books that don't correspond to an existing book, if the Paratext project is not available, changed the code to just remove it (rather than checking to see f it can just be excluded).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glysse …
> PG-1186: Made glyssenshare files for Paratext projects able to cope with missing project

- Glyssen/App.config
- Glyssen/Block.cs
- Glyssen/Project.cs
- Glyssen/Properties/Settings.Designer.cs
- Glyssen/Properties/Settings.settings
- GlyssenTests/Quote/QuoteParserTests.cs
This prevents combining the acrostic headings in Psalm 119 with adjoining poetry paragraphs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/501)
> PG-1203: Distinguished between \qa and other "normal" poetry styles in IsFollowOnParagraphStyle

- Glyssen/Dialogs/AssignCharacterDlg.cs
- Glyssen/Dialogs/BlockNavigatorViewModel.cs
- GlyssenTests/Dialogs/AssignCharacterViewModelTests.cs
When an existing matchup has a single original block, splitting it turns it into a proper multi-block matchup.
Also made small improvement to logging for better future diagnostics
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/503)
> PG-1204: Prevent crash caused by bad matchup indexes following split

- Glyssen/Dialogs/ScriptureRangeSelectionDlg.cs
We always just use existing book when user includes a previously excluded book.
Also improved analytics to only track a "SetSingleVoice" when user **changes** the SingleVoice property.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/511)
> PG-1212: For bundle-based projects, fix logic to not try to get content from Paratext

- Glyssen/Dialogs/ProjectSettingsDlg.cs
When disallowing ChapterAnnouncement options that depend on IncludedBooks, if there are no included books, use all Books instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/518)
> PG-1230: Relax logic to disallow ChapterAnnouncement options based on IncludedBooks

- Glyssen/BlockMatchup.cs
- Glyssen/BookScript.cs
- Glyssen/ReferenceText.cs
- GlyssenTests/BlockMatchupTests.cs
when blocks that are part of a runaway open quote are assigned to narrator.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/521)
> PG-1235: Prevented crash resulting from bad multi-block block chains

- Glyssen/Dialogs/AssignCharacterDlg.Designer.cs
- Glyssen/Dialogs/AssignCharacterDlg.cs
This prevents crashes and general twitchiness when large amounts of data are on the clipboard or when cells contain huge amounts of text.
(DataGridView behaves very poorly when a single row gets taller than the entire control.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/522)
> PG-1238: Fixed special row height adjustment logic

- Glyssen/Glyssen.csproj
- Glyssen/Program.cs
- Glyssen/Utilities/LogFileTraceListener.cs
I implemented this in hopes of getting some useful info to track down ICU load error reported in PG-1234. However, the trace info from ICU do not make it out, so all we get is the trace inf from ParatextData. Still that seems like a useful improvement.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/523)
> Added trace listener to channel trace info from ParatextData into our log file.

- Glyssen/ReferenceText.cs
- GlyssenTests/ReferenceTextTests.cs
when vern has more blocks than the ref text.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/525)
> PG-1246: Prevented duplicate reference text blocks at end of book

- Glyssen/Block.cs
- Glyssen/Dialogs/AssignCharacterViewModel.cs
- Glyssen/Resources/CharacterVerse.txt
- GlyssenShared/BlockElement.cs
- GlyssenTests/BlockTests.cs
- GlyssenTests/Dialogs/AssignCharacterViewModelTests.cs
This addresses both the underlying cause of the crash reported in PG-1257 as well as adding the missing entry (for MAT 27:39) to the factory control file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/528)
> PG-1257: Fixed crash when adding project-specific control file entries

- Glyssen.sln.DotSettings
- Glyssen/App.config
- Glyssen/Dialogs/BlockNavigatorViewModel.cs
- Glyssen/Properties/Settings.Designer.cs
- Glyssen/Properties/Settings.settings
- Glyssen/UsxParser.cs
- GlyssenTests/UsxParserTests.cs
PG-1262: It's not entirely clear whether in some past version of the standard it was considered acceptable to indicate a verse bridge formed by two verse fields with a dash in the text of the first one, but since Paratext does not flag it as an error, I've modified the USX Parser to handle it.
PG-1263: Added check to try to track down mysterious ArgumentOutOfRangeException exception.
Also did a little bit of refactoring and typo cleanup
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/535)
> PG-1262: Changed UsxParser to handle odd verse bridges

- Glyssen/Block.cs
- GlyssenTests/BlockTests.cs
in QuoteParser when block does not end with sentence-ending punctuation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/540)
> PG-1274: list item & footer tags are allowed to combine

- Glyssen/Character/CharacterVerseData.cs
- GlyssenTests/Character/CharacterVerseDataTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/545)
> Merge prevent migration crash when same character occurs in multiple verses of block bridge

- Glyssen/BlockNavigator.cs
- Glyssen/Dialogs/BlockNavigatorViewModel.cs
- GlyssenTests/BlockNavigatorTests.cs
- GlyssenTests/Dialogs/BlockNavigatorViewModelTests.cs
This prevents a crash if the user attempts to navigate to the next relevant block, after failing to load a block based on a reference that corresponds to chapter 0 or verse 0.
Also put in a safeguard against an invalid VerseRef (though currently this can't happen in production code).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/555)
> PG-1289: Prevented inconsistent state in TryLoadBlock

- Glyssen/ReferenceText.cs
- GlyssenTests/ReferenceTextTests.cs
This handles the unlikely (probably caused by using versification that is incompatible with vern text) scenario where there are more chapters in the vernacular than the reference text.
Also noticed and fixed flaw logic that attempts to get things back on track. We were assuming that the vernacular chapter and verse numbers could be used to find correct location in reference text.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/556)
> PG-1279: Prevent index out of range in MatchVernBlocksToReferenceTextBlocks

- Glyssen/Dialogs/QuotationMarksDlg.cs
Note: this crash happened to me when I opened a left-over test project. It might be an impossible -- or at least highly improbable -- scenario for normal projects.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/574)
> Prevent update of test parse if bundle is missing

- ControlDataIntegrityTests/App.config
- ControlDataIntegrityTests/ControlDataIntegrityTests.csproj
- ControlDataIntegrityTests/packages.config
- DevTools/App.config
- DevTools/ControlFiles.Designer.cs
- DevTools/DevTools.csproj
- DevTools/packages.config
- Glyssen/App.config
- Glyssen/Glyssen.csproj
- Glyssen/packages.config
- GlyssenEngineTests/GlyssenEngineTests.csproj
- GlyssenShared/GlyssenShared.csproj
- GlyssenSharedTests/GlyssenSharedTests.csproj
- GlyssenSharedTests/packages.config
- GlyssenTests/App.config
- GlyssenTests/GlyssenTests.csproj
- GlyssenTests/ProjectTests.cs
- GlyssenTests/Properties/Settings.Designer.cs
- GlyssenTests/packages.config
- Installer/Installer.wxs
- RefTextDevUtilities/RefTextDevUtilities.csproj
- RefTextDevUtilities/app.config
- RefTextDevUtilities/packages.config
- Reference Text Utility/App.config
- Reference Text Utility/Properties/Resources.Designer.cs
- Reference Text Utility/Properties/Settings.Designer.cs
- Reference Text Utility/Reference Text Utility.csproj
- Reference Text Utility/packages.config
- build/TestInstallerBuild.bat
Also added package reference to System.ValueTuple to all to avoid conflict warnings and runtime failure.
Removed System.Runtime.InteropServices.RuntimeInformation.dll form Installer (apparently a local copy is no longer needed).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/581)
> PG-1304: Bumped all .Net Framework-based DLLs to 4.7.2

- Glyssen/Dialogs/AssignCharacterViewModel.cs
- GlyssenTests/ProjectTests.cs
Specifically, we want to avoid adding narrator entries, but just in case this ever got called with any other "standard" character type, we'd skip those also.
(This is primarily to prevent spurious Analytics calls, but it should also avoid needless bloat of project-specific files.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/585)
> PG-1309: Prevented addition of project-specific entries for standard characters

- Glyssen/Block.cs
- Glyssen/BookBlockIndices.cs
- Glyssen/DataMigrator.cs
- Glyssen/Dialogs/SplitBlockDlg.cs
- Glyssen/ProjectDataMigrator.cs
- Glyssen/ReferenceText.cs
- Glyssen/Resources/CharacterVerse.txt
- Glyssen/UsxParser.cs
- GlyssenShared/BlockElement.cs
- GlyssenTests/BlockTests.cs
- GlyssenTests/ProjectDataMigratorTests.cs
- GlyssenTests/ReferenceTextTests.cs
Note that the scenario in PG-1311 is probably related to conditions in PG-1310 that we have been unable to reproduce.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/586)
> PG-1311: Prevent crash caused by bug in SplitBlock

- Glyssen/Dialogs/AssignCharacterDlg.cs
- Glyssen/Dialogs/AssignCharacterViewModel.cs
- Glyssen/Dialogs/BlockNavigatorViewModel.cs
- GlyssenTests/Dialogs/BlockNavigatorViewModelTests.cs
Changed SetBlockMatchupForCurrentLocation (formerly SetBlockMatchupForCurrentVerse) to always use the current start index when building a new matchup so that it will cover the correct range even if a subsequent block in the matchup is the "anchor" block. This prevents incorrect display after splitting a block that is not the first block in the matchup.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/587)
> PG-1310: Prevent incorrect matchup display after splitting

- DistFiles/reference_texts/English/JOL.xml
- RefTextDevUtilities/ReferenceTextUtility.cs
Fixed InitialStartVerse in JOL 2:20
Made ReferenceTextUtility able to output FCBH mappings for OT and NT together
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/597)
> PG-1162: Fixes in JOL and ReferenceTextUtility 

- Glyssen/Block.cs
- Glyssen/ProjectDataMigrator.cs
- GlyssenTests/BookScriptTests.cs
- GlyssenTests/Character/CharacterAssignerTests.cs
- GlyssenTests/Dialogs/BlockNavigatorViewModelTests.cs
- GlyssenTests/ProjectDataMigratorTests.cs
- GlyssenTests/ProjectTests.cs
- GlyssenTests/TestProject.cs
Moved Fonts.Default initialization into static constructor for TestPr…ject so that all unit tests that rely on that can be run independently and not depend on the order of tests.
Added early return in MigrateProjectData to avoid logging the no-op case when we're already on the correct version. Note: This means that MigrateDeprecatedCharacterIds will NOT be called if the version is already up-to-date. (I think this should be okay.)
Prevented overwriting a "Needs Review" character assignment in MigrateDeprecatedCharacterIds. (There is some special logic in the parser to assign this when blocks include verses with both implicit and non-implicit characters, and the logic in this method was clobbering those.)
Fixed typos in comments in BlockNavigatorViewModelTests.cs and Block.cs
---
This …
> Fixed flaw in MigrateDeprecatedCharacterIds + misc. improvements (comments, tests)

- Glyssen/Dialogs/AssignCharacterDlg.cs
If "FirstDisplayedCell" is null, skip the logic to try to select the cell and enter edit mode.
Also, suppress display of "nothing matches filter" message when the ISP dialog box is not yet visible.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/604)
> PG-1320: Prevent crash updating reference text grid when not yet displayed

- Glyssen/App.config
- Glyssen/Properties/Settings.Designer.cs
- Glyssen/Properties/Settings.settings
- Glyssen/UsxParser.cs
- GlyssenTests/UsxParserTests.cs
If USX has punctuation following a character style (\qt or \wj) that gets broken off into a separate block and that punctuation appears to belong to the preceding block, append it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/599)
> PG-1298: Prevent orphaned trailing punctuation in USX parser

- Glyssen/Block.cs
- Glyssen/Character/CharacterAssigner.cs
- Glyssen/Project.cs
- Glyssen/ProjectDataMigrator.cs
- Glyssen/Quote/QuoteParser.cs
- GlyssenEngine/Quote/IQuoteInterruptionFinder.cs
- GlyssenEngine/Quote/QuoteInterruption.cs
- GlyssenEngine/Quote/QuoteSystem.cs
- GlyssenTests/BlockTests.cs
- GlyssenTests/BookScriptTests.cs
- GlyssenTests/Character/CharacterAssignerTests.cs
- GlyssenTests/ProjectTests.cs
...rather than having the quote interruption logic be based on the actual quote system in use.
In some cases, the order in which tests were run could potentially lead to failures.
Added some additional Block tests to deal with condition where the quote system did/did not include a long dash.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/610)
> Fixed bad dependency in Block on a static regex

- Glyssen/DataMigrator.cs
- Glyssen/Dialogs/WinFormsMessageBox.cs
- GlyssenEngine/Utilities/MessageModal.cs
Note: Exclamation and Warning are already synonymous, but I'm leaving Exclamation for now to avoid a messy merge conflict since I know the code that uses it is getting moved in a separate PR.
Further paring down should be possible after we refactor things to move more user interaction into the UI layer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/614)
> Pared down MessageModal enums to a more limited set of options.

- Glyssen/Dialogs/SplitBlockViewModel.cs
- Glyssen/Dialogs/UnappliedSplitsViewModel.cs
- GlyssenTests/Dialogs/SplitBlockViewModelTests.cs
It now properly formats the body of the select element to include the block-split ID.
Also removed unassigned member from UnappliedSplitsViewModel to eliminate build warning.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/630)
> PG-1324: Fixed HTML-building logic in SplitBlockViewModel

- GlyssenEngine/Script/Block.cs
- GlyssenEngine/Script/BlockMatchup.cs
- GlyssenEngineTests/Script/BlockMatchupTests.cs
(We allow unmatched blocks to be cross-linked because they are always volatile and never live beyond a matchup, export, etc. But matched blocks are held onto for the life of the owning BookScript, so any subsequent change to a reference text block could potentially change the reference block held as the matched reference block of a vernacular block.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/635)
> PG-1316: Clone reference text blocks in Apply to avoid possibly cross-linking

- Glyssen/App.config
- Glyssen/Dialogs/QuotationMarksDlg.cs
- Glyssen/Properties/Settings.Designer.cs
- Glyssen/Properties/Settings.settings
- GlyssenEngine/Bundle/GlyssenDblTextMetadata.cs
- GlyssenEngine/Project.cs
- GlyssenEngineTests/Bundle/GlyssenBundleTests.cs
- GlyssenEngineTests/ProjectTests.cs
Removed ParserVersion from settings (previously turned into a constant)
Replaced two quote system-related setters in Project with a method that ensures they are called int he required order (made setters private)
Added call to ensure FontRepository implementation is set for all unit tests that need it.
Fixed logic error whereby QuoteSystemDate was not getting updated if the user changed the quote system
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/636)
> Engine-related cleanup and tightening of interface for setting quote system

- GlyssenEngine/Script/BlockMatchup.cs
- GlyssenEngine/Script/BookScript.cs
- GlyssenEngine/ViewModels/BlockNavigatorViewModel.cs
- GlyssenEngineTests/Bundle/GlyssenBundleTests.cs
- GlyssenEngineTests/ProjectTests.cs
- GlyssenEngineTests/Script/BlockMatchupTests.cs
- GlyssenEngineTests/Script/BookScriptTests.cs
- GlyssenEngineTests/TestProject.cs
- GlyssenEngineTests/ViewModelTests/BlockNavigatorViewModelTests.cs
This deals with the In the unusual case where a verse number is repeated in two adjacent blocks.
Simplified a couple BlockMatchup methods that were taking Versification. (We can get that from the book now.)
Fixed problem in unit tests where we were getting a data migration warning because we were accessing Project class before setting GlyssenInfo.Product to the test folder.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/650)
> PG-1336: Prevent creation of matchup that splits between two blocks that end/start with same verse

- GlyssenEngineTests/Rules/CharacterGroupGeneratorTests.cs
- GlyssenSharedTests/packages.config
- build/TestBuild.bat
This should ensure that worker thread finishes before checking results and ending the test, preventing this test from affecting another case in the same fixture.
Also Upgraded GlyssenSharedTests to latest version of NUnit 3.
(Note: I had previously added this attribute to the one test that had begun failing on TeamCity, but I couldn't find any reason why any of these tests could safely be run in parallel, so I wanted to apply that decision to all of them and document why.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/652)
> Reworked plumbing in GenerateCharacterGroups_IsCancelable

- GlyssenEngine/ViewModels/AssignCharacterViewModel.cs
- GlyssenEngine/ViewModels/SplitBlockViewModel.cs
In rainbow mode, we were only getting the characters for the piece of the block that corresponded to the current matchup block (which is often only part of the corresponding original block.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/655)
> PG-1343: When splitting a block, ensure that all relevant characters are included

- ControlDataIntegrityTests/ControlDataIntegrityTests.csproj
- ControlDataIntegrityTests/packages.config
- DevTools/DevTools.csproj
- DevTools/packages.config
- DistFiles/localization/Glyssen.es.tmx
- Glyssen/Glyssen.csproj
- Glyssen/Program.cs
- Glyssen/Utilities/AlertImpl.cs
- Glyssen/Utilities/ProgressUtilsImpl.cs
- Glyssen/packages.config
- GlyssenEngine/DataMigrator.cs
- GlyssenEngine/GlyssenEngine.csproj
- GlyssenEngine/Project.cs
- GlyssenEngine/ProjectBase.cs
- GlyssenEngine/ReferenceText.cs
- GlyssenEngine/Utilities/GlyssenVersificationTable.cs
- GlyssenEngine/Utilities/StringExtensions.cs
- GlyssenEngineTests/GlyssenEngineTests.csproj
- GlyssenEngineTests/Utilities/StringExtensionsTests.cs
- GlyssenEngineTests/packages.config
- GlyssenShared/GlyssenShared.csproj
- GlyssenSharedTests/GlyssenSharedTests.csproj
- GlyssenSharedTests/packages.config
- GlyssenTests/GlyssenTests.csproj
- GlyssenTests/packages.config
- RefTextDevUtilities/RefTextDevUtilities.csproj
- RefTextDevUtilities/packages.config
- Reference Text Utility/Reference Text Utility.csproj
- Reference Text Utility/packages.config
Previous behavior (accidentally, because of a change in SIL.Scripture) suppressed the error reporting and used the resulting versification, which might be bogus. Now we alert the user as appropriate.
Note: this is a pre-requisite to completion of https://github.com/sillsdev/Glyssen/pull/659
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/660)
> Instead of having errors in versification files ignored, alert the user

- GlyssenEngine/Bundle/GlyssenDblTextMetadata.cs
- GlyssenEngine/Project.cs
- GlyssenEngine/ReferenceText.cs
- GlyssenEngine/Script/BlockMatchup.cs
- GlyssenEngine/Script/BookScript.cs
- GlyssenEngine/ViewModels/BlockNavigatorViewModel.cs
- GlyssenEngineTests/ProjectTests.cs
- GlyssenEngineTests/Script/BlockMatchupTests.cs
- GlyssenEngineTests/ViewModelTests/AssignCharacterViewModelTests.cs
- GlyssenEngineTests/ViewModelTests/BlockNavigatorViewModelTests.cs
- GlyssenShared/Bundle/GlyssenDblMetadataLanguage.cs
Initial implementation to detect and store reporting clauses and generate the corresponding "he said" reference blocks in GetBlocksForVerseMatchedToReferenceText.
This includes the migration of the "heSaid" element to "reportingClause" (now a list)
(Also fixed a few typos/misspellings)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/662)
> PG-1329: Recognize "he said" text and automatically apply to other blocks

- GlyssenEngine/Project.cs
- GlyssenEngine/Utilities/ListExtensions.cs
- GlyssenEngineTests/GlyssenEngineTests.csproj
- GlyssenEngineTests/Utilities/ListExtensionsTests.cs
AddMissingAvailableBooks was incorrectly assuming that m_books would not have "holes." I write a really cool general-purpose merge method to fix this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/667)
> PG-1352: Prevented crash when Paratext project has book names defined for unavailable books

- GlyssenFileBasedPersistence/PersistenceImplementation.cs
This should prevent UnauthorizedAccessException: Access to the path 'C:\Program Files\Glyssen\reference_texts\English\english.glyssen' is denied.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/675)
> PG-1366: When getting a TextReader, open file with read-only access.

- DistFiles/reference_texts/Russian/russian.glyssen
- Glyssen/Dialogs/ProjectSettingsDlg.cs
- GlyssenEngine/ReferenceText.cs
based on selected reference text, since it may be out of sync with latest English version.
Also fixed logic that selects the current reference text so that if user localizes on the fly, the same one is re-selected.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/687)
> PG-1376: Made display of English version of reference text update

- .nuget/NuGet.targets
- CHANGELOG.md
- ControlDataIntegrityTests/ControlDataIntegrityTests.csproj
- ControlDataIntegrityTests/packages.config
- DevTools/DevTools.csproj
- DevTools/packages.config
- Glyssen/Glyssen.csproj
- GlyssenEngine/GlyssenEngine.csproj
- GlyssenEngineTests/GlyssenEngineTests.csproj
- GlyssenEngineTests/packages.config
- GlyssenTests/GlyssenTests.csproj
- GlyssenTests/packages.config
- RefTextDevUtilities/RefTextDevUtilities.csproj
- RefTextDevUtilities/packages.config
This change includes the CHANGELOG update and an upgrade to PartextDat 9.1.7-beta to resolve an issue with the Installer when upgrading from a previous version of Glyssen.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/688)
> v1.3.13 Final changes for release

- GlyssenEngine/GitVersion.yml
- GlyssenShared/GitVersion.yml
We only want releases to be created when a commit is tagged with a version number. All others shoud be beta.
This approach might not be correct since gitversion CLI returns a warning about ambiguity between the base gitversion.yml file (in the solution dir) and the ones in the project folders. But it appears that (at least on Appveyor) the yml file in the project folder is the one that wins.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/695)
> Prevent creation of release packages on nuget whenever a PR is merged into master

- GlyssenEngine/Quote/ParserCharacterRepository.cs
- GlyssenEngineTests/GlyssenEngineTests.csproj
- GlyssenEngineTests/Quote/ParserCharacterRepositoryTests.cs
Ignore Hypothetical quotes types when the reference text is unavailable. This was done because Vessel does not assign a reference text.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/716)
> For Vessel: Ignore Hypothetical quotes types when reference text = null

- GlyssenEngine/Resources/Annotations.txt
- GlyssenEngineTests/Export/ProjectExporterTests.cs
- GlyssenShared/BlockElement.cs
- RefTextDevUtilities/ReferenceTextUtility.cs
MarkW (FCBH) inquired and found out that post-processing does not need the 1-minute pause at the end of REV.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/726)
> TXL-1399: Pause at end of REV reduced to 5 seconds

- Glyssen/Dialogs/AssignCharacterDlg.cs
- GlyssenEngine/ReferenceText.cs
- GlyssenEngine/Script/Block.cs
- GlyssenEngine/Script/BlockMatchup.cs
- GlyssenEngine/ViewModels/BlockNavigatorViewModel.cs
- GlyssenEngineTests/ReferenceTextTests.cs
- GlyssenEngineTests/Script/BlockMatchupTests.cs
- GlyssenEngineTests/Script/BlockTests.cs
- GlyssenEngineTests/ViewModelTests/BlockNavigatorViewModelTests.cs
Note: this might also solve PG-1403
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/723)
> PG-1404: Prevent crash switching to Select Character mode when matchup's first block is not relevant

- GlyssenEngine/ReferenceText.cs
- GlyssenEngine/Script/Block.cs
- GlyssenEngine/Script/BlockMatchup.cs
- GlyssenEngine/Script/BookScript.cs
- GlyssenEngine/ViewModels/BlockNavigatorViewModel.cs
- GlyssenEngineTests/ReferenceTextTests.cs
- GlyssenEngineTests/Script/BlockMatchupTests.cs
- GlyssenEngineTests/Script/BlockTests.cs
- GlyssenShared/BlockElement.cs
PG-1408 [Part 1]: Prevent detection of omissible "he said" reference block when there is additional following text.
Also, improve block matchup logic to assign narrator to the correlated block when the vernacular text starts with an apparent dialogue closing dash.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/729)
> PG-1408: Prevent detection of omissible "he said" reference block when there is additional following text

- GlyssenEngine/ReferenceText.cs
- GlyssenEngineTests/ReferenceTextTests.cs
Added logic to allow bottom-up matching to proceed when a trailing he-said has been pre-matched.
Added logic to find and use an exact match (if any) if multiple vern blocks are unmatched and there is only one remaining unmatched ref block.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/737)
> PG-1423: Improvements to ref text matching logic when target has he saids

- Glyssen/Dialogs/AssignCharacterDlg.cs
This could happen when a selection was made in a reference text cell that cannot be split.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/744)
> PG-1427: prevented NullReferenceException when in Split Mode

- Glyssen/Dialogs/AssignCharacterDlg.cs
When it is being "changed" to the same value it had, for some reason the grid is considering it to be "dirty" and in need of validation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/750)
> Prevent spurious warning about changing the character for a continuation block

- GlyssenEngine/ReferenceText.cs
- GlyssenEngineTests/ReferenceTextTests.cs
Specific scenario is when reporting clauses in reference text are combined into a single block that comes between the two speaking parts in the vernacular.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/762)
> PG-1431: Fixed alignment problem

- Glyssen/Dialogs/AssignCharacterDlg.cs
- GlyssenEngine/Script/Block.cs
- GlyssenEngineTests/Script/BlockTests.cs
Prevent moving verse number when current corresponding vern row has a verse/bridge that overlaps with reference verse/bridge.
Also take versification differences into account.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/768)
> +semver:major PG-1441: Fix bug caused by PG-1425

- GlyssenShared/GlyssenShared.csproj
Usually there is no need to make the nuget package depend on SIL.ReleaseTasks. It is a build-time dependency that is needed when building the nuget package but isn't required at runtime.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/774)
> Make SIL.ReleaseTasks a build-only dependency

- GlyssenEngine/GlyssenEngine.csproj
Usually there is no need to make the nuget package depend on SIL.ReleaseTasks. It is a build-time dependency that is needed when building the nuget package but isn't required at runtime.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/773)
> Make SIL.ReleaseTasks  a build-only dependency

- GlyssenEngine/Project.cs
- GlyssenEngine/ReferenceText.cs
- GlyssenEngine/Script/Block.cs
- GlyssenEngineTests/ReferenceTextTests.cs
Also added code to move verse number to preceding English reference block when moving it for a non-English reference block.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/775)
> PG-1408: Improvements to prevent loss of reference text.

- GlyssenEngine/Script/BlockMatchup.cs
- GlyssenEngine/Script/BookScript.cs
when applying the correlated blocks of a BlockMatchup to ensure preceding blocks are in a valid state. This avoids an exception caused by calling it prematurely before trailing narrator blocks have their MultiBlockQuote property set to None.
Note: issue is duplicated by: PG-1437 and PG-1438.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/776)
> PG-1436: Changed when UpdateFollowingContinuationBlocks gets called

- GlyssenEngine/ReferenceText.cs
- GlyssenEngineTests/ReferenceTextTests.cs
Added check to prevent automatic matching to multiple reference text blocks with a different end ref if the last one has an unexpected characters speaking.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/781)
> PG-1458: Prevent unreported reference text mismatch when reference text has error

- GlyssenEngine/Script/BookScript.cs
- GlyssenEngine/ViewModels/BlockNavigatorViewModel.cs
- GlyssenEngineTests/Script/BookScriptTests.cs
with details to try to figure out what happened if this error occurs again in the future.
Also (possibly related?) improved GetIndexOfFirstBlockForVerse to handle case of "Scripture" (?) block before v. 1.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/788)
> PG-1462: Added some crash-proofing code to LoadNextRelevantBlock

- GlyssenEngine/ReferenceText.cs
- GlyssenEngine/Script/Block.cs
- GlyssenEngine/ViewModels/BlockNavigatorViewModel.cs
- GlyssenEngineTests/Script/BlockTests.cs
- GlyssenEngineTests/ViewModelTests/AssignCharacterViewModelTests.cs
1. when matchup is applied but the block remains relevant
2. when project is updated (or the user leaves and comes back into the ISP dialog) and the number of blocks in previously selected matchup has changed
3. when moving contents of reference text cell and a preceding row is a section head
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/790)
> PG-1468: Prevent errors in three scenarios

- GlyssenEngine/ReferenceText.cs
- GlyssenEngineTests/ReferenceTextTests.cs
(similar to PG-1277, but a different scenario) when a verse is missing in the target text but it is combined with the start of the following verse in the reference text.
Also fixed some edge cases where the forceMatch flag was not being taken into account.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/792)
> Fixed problems in reference text matching (especially for single-voice books)

- DistFiles/reference_texts/English/LUK.xml
- DistFiles/reference_texts/Russian/LUK.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/805)
> Fixed incorrect character ID in LUK 9:8 in reference texts

- GlyssenEngine/ReferenceText.cs
- GlyssenEngineTests/ReferenceTextTests.cs
As part of this, also fixed an actual bug where the reference text could be changed as part of the alignment process without the change being noted so that the reference text would get reloaded.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/809)
> Improved alignment of reference text to the vernacular for narrator-only books

- CHANGELOG.md
- DistFiles/ReleaseNotes.md
- Glyssen/Dialogs/AssignCharacterDlg.Designer.cs
- Glyssen/Dialogs/AssignCharacterDlg.cs
- GlyssenEngine/ViewModels/AssignCharacterViewModel.cs
- GlyssenEngineTests/ViewModelTests/AssignCharacterViewModelTests.cs
Added AssignCharacterViewModel.GetVerseRefForRow and code in AssignCharacterDlg to send the ref as a "Santa Fe" message so Paratext and other participating apps will go to the current reference when the user clicks in a reference text row.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/817)
> PG-1360: Implemented "Synchronized scrolling" when user clicks in a reference text row

- Glyssen/Program.cs
I'm really mystified as to why/how the .* was ever added. We only put it on one of the two. Looking at the code in L10nSharp (see line 194 in StringExtractor.cs), I can't see how .* could ever have worked, and that code is essentially the same as it has been for at least 10 years. Oddly, I couldn't detect any difference between having and not having it, but I suspect that is because it just uses the checked-in version of the English xlf file rather than (or in addition to) scanning for new strings, and maybe (I guess) our checked in file has all the strings from those two namespaces.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/818)
> Removed .* from end of namespace spec in call to LocalizationManage.Create

- ControlDataIntegrityTests/CharacterVerseDataTests.cs
- DevTools/CharacterVerseUpdater.cs
- GlyssenCharacters/Resources/CharacterVerse.txt
Also reverted a couple places where Potential lines were inadvertently changed to Implicit, and improved updater code so that Potential speech wouldn't get updated in the future.
Also added check in integrity tests to make sure quote position is not set for quote types where it makes no sense.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/Glyssen/845)
> Stripped off the meaningless "Unspecified" quote position for Potential speech

- ControlDataIntegrityTests/CharacterVerseDataTests.cs
- DevTools/CharacterVerseUpdater.cs
- DevTools/Program.cs
- GlyssenCharacters/Resources/CharacterVerse.txt
We realized that the change to mark so many verses as Implicit did not really reflect the intention of that type, and actually made it harder for a user distinguish between normal and implicit for the purpose of deciding when it was appropriate to use quotation marks.
Also marked a couple longer discourses in GEN (ch 24 & ch 44) as Implicit.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/Glyssen/848)
> PTX-22920: Reverted the changes from Normal, Dialogue, and Quotation to Implicit

- GlyssenTests/GlyssenTests.csproj
- GlyssenTests/packages.config
- Reference Text Utility/Reference Text Utility.csproj
This DLL is referenced explicitly only in tests and and Reference Text Utility, but that causes the referenced version to end up in the output folder, where it is picked up by the installer. ParatextData.DLL references the slightly older version, which causes a FileLoadException when doing string extraction.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/Glyssen/852)
> PG-1493: Rolled back MarkDig.Signed to v. 0.30.4

- CHANGELOG.md
- Glyssen/Dialogs/AddCharacterDlg.cs
- GlyssenCharacters/CharacterVerseData.cs
- GlyssenCharacters/ControlCharacterVerseData.cs
- GlyssenCharacters/Resources/CharacterVerse.txt
- GlyssenCharactersTests/CharacterVerseDataTests.cs
- GlyssenCharactersTests/ControlCharacterVerseDataTests.cs
- GlyssenEngine/Character/CombinedCharacterVerseData.cs
- GlyssenEngine/ProjectDataMigrator.cs
- GlyssenEngine/ViewModels/AssignCharacterViewModel.cs
Also, prevent the user from assigning or adding any ID that would be considered extra-biblical.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/Glyssen/854)
> PG-1494/PG-1495: Do not allow an interruption ID to be assigned to a block

- DevTools/DevTools.csproj
- DevTools/packages.config
- Glyssen/Glyssen.csproj
- GlyssenTests/App.config
- GlyssenTests/GlyssenTests.csproj
- GlyssenTests/packages.config
- Reference Text Utility/Reference Text Utility.csproj
This prevents NullReferenceException because of MarkDig.Signed version mismatch between Glyssen and ParatextData
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/Glyssen/871)
> PG-1502: Use patched version of L10nSharp

- Glyssen.sln.DotSettings
- Glyssen/Dialogs/ScriptureRangeSelectionDlg.cs
- Glyssen/MainForm.cs
- GlyssenEngine/Paratext/ParatextProjectBookInfo.cs
- GlyssenEngine/Project.cs
Fixed bug in ScriptureRangeSelectionDlg where OK button could be incorrectly disabled.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/Glyssen/878)
> Fixed UX edge cases when project books contain no Scripture data
