- Glyssen/Controls/DataGridViewOverrideEnter.cs
- Glyssen/Controls/DataGridViewOverrideEnter.resx
- Glyssen/Controls/VoiceActorInformationGrid.Designer.cs
- Glyssen/Controls/VoiceActorInformationGrid.cs
- Glyssen/Controls/VoiceActorInformationGrid.resx
- Glyssen/Dialogs/VoiceActorAssignmentDlg.Designer.cs
- Glyssen/Dialogs/VoiceActorAssignmentDlg.cs
- Glyssen/Dialogs/VoiceActorAssignmentDlg.resx
- Glyssen/Dialogs/VoiceActorInformationDlg.Designer.cs
- Glyssen/Dialogs/VoiceActorInformationDlg.cs
- Glyssen/Dialogs/VoiceActorInformationDlg.resx
- Glyssen/Glyssen.csproj
- Glyssen/MainForm.cs
- Glyssen/Project.cs
- Glyssen/VoiceActor/VoiceActorEntity.cs
- Glyssen/VoiceActor/VoiceActorList.cs
Constructed shell of Voice Actor Information window based on design document.
I was unable to implement a move to next field on combobox item selection.
Todo: implement buttons (save/next)
> PG-234 Initial construction of Voice Actor info dialog

- Glyssen/Character/CharacterGroup.cs
- Glyssen/Character/CharacterGroupList.cs
- Glyssen/Dialogs/VoiceActorAssignmentDlg.Designer.cs
- Glyssen/Dialogs/VoiceActorAssignmentDlg.cs
- Glyssen/Program.cs
- GlyssenTests/Character/CharacterGroupListTests.cs
Current implementation utilizing calculation based on keystrokes spoken per hour.
> PG-263 Populate "Hours" field in VA Assign

- Glyssen/Dialogs/VoiceActorAssignmentDlg.Designer.cs
- Glyssen/Dialogs/VoiceActorAssignmentDlg.cs
- Fixed tabbing between controls
- F6 toggles between tables
- Fixed aesthetic flaw in VA assign paneling
> PG-260 VA Assign tab between tables

- Glyssen/Controls/VoiceActorInformationGrid.cs
Drop down opens on cell entrance
> Improvements to navigation in VA info grid comboboxes

- Glyssen/Dialogs/QuotationMarksDlg.Designer.cs
- Glyssen/Dialogs/VoiceActorAssignmentDlg.Designer.cs
- Glyssen/Dialogs/VoiceActorInformationDlg.Designer.cs
Also, VA windows center on parent and don't show in task bar.
> PG-316 Minimize removed on modals

- Glyssen/Controls/VoiceActorInformationGrid.cs
- Glyssen/Dialogs/VoiceActorAssignmentDlg.Designer.cs
- Glyssen/Dialogs/VoiceActorAssignmentDlg.cs
- Glyssen/Dialogs/VoiceActorAssignmentDlg.resx
Todo: don't show context menus on lower blue part of grids
> PG-300 VA Assign context menus

- Glyssen/Controls/SaveStatus.cs
- Glyssen/Controls/VoiceActorInformationGrid.cs
- Glyssen/Dialogs/AssignCharacterDlg.Designer.cs
- Glyssen/Dialogs/VoiceActorAssignmentDlg.cs
- Glyssen/Dialogs/VoiceActorInformationDlg.Designer.cs
- Removed Save button in VA Info
- Expanded SaveStatus in character assign to show full status
- Rearranged SaveStatus message
- Updated EditMode on VA Info grid to allow deletion of actors (made impossible for VA Info Dlg with switch to EditOnEnter)
> Save UI Updates

- Glyssen/Controls/DataGridViewListBox.cs
- Glyssen/Dialogs/VoiceActorAssignmentDlg.cs
- Other cells (e.g. attributes) in expanded row have word wrap
- ListBox background is white instead of gray
- Multiselect is fixed
> Minor improvements to character group expansion

- Glyssen/Dialogs/MoveCharactersToGroupUndoAction.cs
- GlyssenTests/Dialogs/MoveCharactersToGroupUndoActionTests.cs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/61)
> Do not remove the group when the role is removed from a cameo actor

- Glyssen/Dialogs/ProjectSettingsDlg.cs
- Glyssen/MainForm.cs
- Glyssen/Program.cs
- Glyssen/Project.cs
Also check if the project file is writable.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/60)
> Set the Glyssen data directory to be full control for everyone

- Glyssen/Quote/QuoteUtils.cs
- GlyssenTests/Quote/QuoteUtilsTests.cs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/64)
> PG-504: Update quote continuers to match those coming from Paratext

- Glyssen/Bundle/GlyssenDblTextMetadata.cs
- Glyssen/Dialogs/ExportDlg.cs
- Glyssen/MainForm.Designer.cs
- Glyssen/MainForm.cs
Also provide a link to open the directory
Resolves #PG-513
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/66)
> PG-513: Display location of most recent export

- Glyssen/Dialogs/AddCharacterToGroupDlg.Designer.cs
- Glyssen/Dialogs/AddCharacterToGroupDlg.cs
- Glyssen/Dialogs/AddCharacterToGroupDlg.resx
- Glyssen/Dialogs/AddCharactersToGroupViewModel.cs
- Glyssen/Dialogs/AssignCharacterDlg.cs
- Glyssen/Dialogs/VoiceActorAssignmentDlg.Designer.cs
- GlyssenTests/Dialogs/AddCharactersToGroupViewModelTests.cs
- GlyssenTests/GlyssenTests.csproj
Also added unit tests for AddCharactersToGroupViewModel.cs
Resolves #PG-500
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/67)
> PG-500: Finish implementing the Add Characters to Group dialog

- Glyssen/Quote/QuoteParser.cs
- GlyssenTests/Quote/QuoteParserTests.cs
Parenthesis was working, but not brackets or braces
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/68)
> Fix StartsWithSpecialOpeningPunctuation

- Glyssen/Dialogs/QuotationMarksDlg.Designer.cs
- Glyssen/Dialogs/QuotationMarksDlg.cs
- Glyssen/Quote/QuoteParser.cs
- Glyssen/Quote/QuoteSystem.cs
- GlyssenTests/Quote/QuoteParserTests.cs
Implement dialog quotes only
Resolves #PG-482
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/69)
> PG-482: Update quotation mark setup dialog

- Glyssen/Dialogs/QuotationMarksDlg.Designer.cs
- Glyssen/Dialogs/QuotationMarksDlg.cs
Add "Test" button on quotation marks dialogue
Resolves PG-483
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/70)
> PG-483: Add test button

- Glyssen/Controls/DataGridViewDropdownColumnHeader.cs
- Glyssen/Dialogs/ScriptureRangeSelectionDlg.cs
- Glyssen/Glyssen.csproj
Resolves #PG501
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/72)
> Issue PG-501: Add Select and Clear All for books

- Glyssen/Dialogs/AssignCharacterDlg.Designer.cs
- Glyssen/Dialogs/AssignCharacterDlg.cs
Resolved #PG-533
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/74)
> Issue PG-533: Checkbox label being truncated

- Glyssen/MainForm.Designer.cs
- Glyssen/MainForm.cs
Resolves #PG-541
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/73)
> PG-541: Clear form and show progress when opening project

- Glyssen/Quote/QuoteParser.cs
- GlyssenTests/Quote/QuoteParserTests.cs
Consider making the quote system in the quote parser a static member to improve performance.
Resolves #PG-171
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/78)
> Issue PG-171: Make the quote system in the quote parser static

- Glyssen/ProjectExporter.cs
If the UI language is not English, export another column for the localized character names.
Resolves #PG-256
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/81)
> PG-256: Add column for localized character names

- Glyssen/Analysis/ProjectAnalysis.cs
- Glyssen/Dialogs/AssignCharacterDlg.cs
- Glyssen/Dialogs/AssignCharacterViewModel.cs
- Glyssen/Dialogs/BlockNavigatorViewModel.cs
- Glyssen/Dialogs/ScriptureRangeSelectionDlg.cs
- GlyssenTests/Dialogs/AssignCharacterViewModelTests.cs
Checking or unchecking "This book will be narrated" in character assignment should not change any assignments.
Update filters and percent completed.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/80)
> Issue PG-317: Single-voice should not change saved assignments

- Glyssen/Resources/CharacterDetail.txt
- Glyssen/Resources/CharacterVerse.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/84)
> Two minor additions to the control file

- Glyssen/BookScript.cs
- Glyssen/Quote/QuoteParser.cs
- GlyssenTests/Character/CharacterAssignerTests.cs
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/83)
> Prevent loss of character info when updating a project based on a new control file (PG-595)

- Glyssen/Quote/QuoteParser.cs
- GlyssenTests/Quote/QuoteParserTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/85)
> Correct logic for determining if dialogue quote is being continued (PG-589)

- build/Glyssen.proj
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/92)
> Fixed rsync args for upload to software.sil.org 2

- build/Glyssen.proj
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/91)
> Attempt to fix rsync by syncing each file rather than using a wildcard

- build/Glyssen.proj
- The web user is vu2004, the dropbox user is not.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/94)
> Fix Upload: Make the file owner match that of the dropbox user

- Glyssen/Bundle/GlyssenDblTextMetadata.cs
- Glyssen/Controls/CastSizePlanningOptions.Designer.cs
- Glyssen/Controls/CastSizePlanningOptions.cs
- Glyssen/Controls/CastSizePlanningOptions.resx
- Glyssen/Dialogs/CastSizePlanningDlg.Designer.cs
- Glyssen/Dialogs/CastSizePlanningDlg.cs
- Glyssen/Dialogs/CastSizePlanningDlg.resx
- Glyssen/Dialogs/CastSizePlanningViewModel.cs
- Glyssen/Dialogs/HtmlMessageDlg.cs
- Glyssen/Glyssen.csproj
- Glyssen/MainForm.cs
- Glyssen/Project.cs
- Glyssen/Utilities/StringExtensions.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/96)
> PG-591: Create cast size planning dialog

- Glyssen/Bundle/GlyssenDblTextMetadata.cs
- Glyssen/Controls/CastSizePlanningOptions.cs
- Glyssen/Dialogs/CastSizePlanningDlg.cs
- Glyssen/Dialogs/CastSizePlanningViewModel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/97)
> Changes from code review

- Glyssen/Dialogs/ExportDlg.cs
- Glyssen/Dialogs/ExportViewModel.cs
- Glyssen/Glyssen.csproj
- Glyssen/MainForm.Designer.cs
- Glyssen/MainForm.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/98)
> Move export code out of the ExportDlg into ExportViewModel

- Glyssen/Dialogs/ExportDlg.cs
- Glyssen/Dialogs/ExportViewModel.cs
- Glyssen/Dialogs/ViewScriptDlg.Designer.cs
- Glyssen/Dialogs/ViewScriptDlg.cs
- Glyssen/Dialogs/ViewScriptDlg.resx
- Glyssen/Glyssen.csproj
- Glyssen/MainForm.Designer.cs
- Glyssen/MainForm.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/99)
> Add the View Script dialog

- ControlDataIntegrityTests/Properties/AssemblyInfo.cs
- DevTools/Properties/AssemblyInfo.cs
- DevTools/TermTranslator/Processor.cs
- Glyssen/Properties/AssemblyInfo.cs
- GlyssenTests/Properties/AssemblyInfo.cs
- Installer/template.download_info
- build/Glyssen.proj
- build/TestInstallerBuild.bat
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/101)
> Version is alpha 0.100.x.x

- Glyssen/Rules/CharacterGroupGenerator.cs
- GlyssenTests/Rules/TrialGroupConfigurationTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/102)
> Fix crash constructing TrialGroupConfiguration with one male actor

- Glyssen/BookMetadata.cs
- GlyssenTests/BookMetadataTests.cs
- GlyssenTests/Rules/CharacterGroupGeneratorTests.cs
- GlyssenTests/Rules/CharacterGroupsAdjusterTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/106)
> Default the Epistles to single voice

- Glyssen/Dialogs/CastSizePlanningDlg.cs
- Glyssen/Dialogs/HtmlMessageDlg.Designer.cs
- Glyssen/Dialogs/HtmlMessageDlg.cs
Hide link labels whose message is incomplete or not implemented.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/110)
> PG-640 and PG-641: Hide some link labels

- Glyssen/Dialogs/SplitCharacterGroupDlg.Designer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/108)
> PG-637: Fix spelling mistake

- Glyssen/Dialogs/AssignCharacterDlg.cs
- Glyssen/Dialogs/OpenProjectDlg.cs
- Glyssen/Dialogs/ProjectSettingsDlg.cs
- Glyssen/Dialogs/VoiceActorAssignmentDlg.cs
- Glyssen/Dialogs/VoiceActorInformationDlg.cs
- Glyssen/MainForm.cs
- Glyssen/Utilities/FormWithPersistedSettings.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/107)
> Tile grandchildren of the main form

- Glyssen/Program.cs
Do not allow more than one instance of Glyssen to be running.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/111)
> PG-634: Only one instance of Glyssen

- Glyssen/Dialogs/AssignCharacterDlg.Designer.cs
- Glyssen/Dialogs/VoiceActorInformationDlg.cs
Also update text of AssignCharacterDlg to match the button text on the main form
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/113)
> PG-642: Disable help button in VoiceActorInformationDlg

- Glyssen/Controls/VoiceActorInformationGrid.cs
When the user clicks in the [new actor] box, set the focus and show the cursor so he knows he can start typing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/115)
> PG-638: Make Adding a New Actor a one-click process

- Glyssen/BookMetadata.cs
- GlyssenTests/BookMetadataTests.cs
- GlyssenTests/Rules/CharacterGroupGeneratorTests.cs
- GlyssenTests/Rules/CharacterGroupsAdjusterTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/119)
> Undo "Default the Epistles to single voice"

- Glyssen/Dialogs/ProjectSettingsDlg.Designer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/123)
> PG-657: Fix tab order on Project Settings dialog

- Glyssen/Controls/ScriptBlocksGridView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/122)
> PG-611: Allow reference column to be resized

- Glyssen/Dialogs/CastSizePlanningViewModel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/124)
> Increase the numbers of male actors

- Glyssen/Dialogs/AssignCharacterDlg.Designer.cs
- Glyssen/Dialogs/AssignCharacterDlg.cs
- Glyssen/Dialogs/QuotationMarksDlg.cs
- Glyssen/Glyssen.csproj
- Glyssen/Utilities/L10N.cs
Also localizes the filter list items
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/126)
> PG-582: Add "All quotes" filter to Assign Characters dialog

- Glyssen/Dialogs/BlockNavigatorViewModel.cs
- GlyssenTests/Dialogs/BlockNavigatorViewModelTests.cs
Verses with Missing Expected Quote filter not working correctly with verse bridges
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/129)
> PG-597: filter not working correctly with verse bridges

- Glyssen/Dialogs/VoiceActorInformationDlg.Designer.cs
Since we are now guessing the actor's gender when the actors name is typed in the Assigned column of Roles for Voice Actors, improve the main instruction in Voice Actor List.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/130)
> PG-668: Voice Actor List attributes instruction

- Glyssen/Dialogs/VoiceActorAssignmentDlg.cs
- Glyssen/MainForm.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/131)
> PG-669: Helpful message if actor assignment had to be removed

- Glyssen/Rules/CharacterGroupGenerator.cs
Make sure the actor is not assigned to more than one group. This happens regularly when the gender of an actor is changed from male to female.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/132)
> PG-665: Crash generating groups after correcting actor gender

- Glyssen/Dialogs/CastSizePlanningDlg.Designer.cs
- Glyssen/Dialogs/CastSizePlanningDlg.cs
If cast size has fewer adult actors of a particular gender than required for the selected narrator preferences, user should be alerted.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/133)
> PG-673: Show alert if more narrators than actors

- DevTools/AnnotationExtractor.cs
- DevTools/DevTools.csproj
- DevTools/Program.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/138)
> Add DevTool for extracting annotations (sound effects, etc.) (PG-683)

- Glyssen/App.config
- Glyssen/Properties/Settings.Designer.cs
- Glyssen/Properties/Settings.settings
- Glyssen/Quote/QuoteParser.cs
- Glyssen/Quote/QuoteSystemGuesser.cs
- GlyssenTests/Quote/QuoteParserTests.cs
- GlyssenTests/Quote/QuoteSystemGuesserTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/141)
> Fix quotation dash ending when there are multiple matched quote marks (PG-589)

- Glyssen/Dialogs/VoiceActorAssignmentViewModel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/148)
> Sort Group Id in natural order

- Glyssen/Block.cs
- Glyssen/Resources/CharacterDetail.txt
- Glyssen/Resources/CharacterVerse.txt
Added character-verse info for the book of Proverbs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/150)
> Pg677 Proverbs

- ControlDataIntegrityTests/Properties/AssemblyInfo.cs
- DevTools/Properties/AssemblyInfo.cs
- DevTools/TermTranslator/Processor.cs
- Glyssen/Properties/AssemblyInfo.cs
- GlyssenTests/Properties/AssemblyInfo.cs
- Installer/template.download_info
- build/Glyssen.proj
- build/TestInstallerBuild.bat
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/151)
> master branch is ready for 0.11.x

- Glyssen/Quote/QuoteParser.cs
- GlyssenTests/Quote/QuoteParserTests.cs
- GlyssenTests/Rules/CharacterGroupGeneratorTests.cs
Parse error if there are characters between special opening punctuation and quote mark
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/149)
> PG-695: Parse error with special opening punctuation

- Glyssen/Dialogs/VoiceActorAssignmentDlg.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/152)
> PG-696: Detail grid can stay open for duration of the window

- Glyssen/Resources/CharacterVerse.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/155)
> Minor correction to control file

- Glyssen/ReferenceText.cs
- GlyssenTests/ReferenceTextTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/157)
> Fixed bug with splitting of vernacular based on reference text (PG-704)

- Glyssen/Quote/QuoteParser.cs
- GlyssenTests/Quote/QuoteParserTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/159)
> Fix bug in quote parser related to opening punctuation (PG-705)

- Glyssen/MainForm.cs
- Glyssen/Project.cs
- Glyssen/ProjectDataMigrator.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/162)
> Two fixes for converting legacy projects (PG-708)

- DistFiles/reference_texts/English/1CO.xml
- DistFiles/reference_texts/English/1JN.xml
- DistFiles/reference_texts/English/1PE.xml
- DistFiles/reference_texts/English/1TH.xml
- DistFiles/reference_texts/English/1TI.xml
- DistFiles/reference_texts/English/2CO.xml
- DistFiles/reference_texts/English/2JN.xml
- DistFiles/reference_texts/English/2PE.xml
- DistFiles/reference_texts/English/3JN.xml
- DistFiles/reference_texts/English/ACT.xml
- DistFiles/reference_texts/English/EPH.xml
- DistFiles/reference_texts/English/GAL.xml
- DistFiles/reference_texts/English/HEB.xml
- DistFiles/reference_texts/English/JAS.xml
- DistFiles/reference_texts/English/JHN.xml
- DistFiles/reference_texts/English/JUD.xml
- DistFiles/reference_texts/English/LUK.xml
- DistFiles/reference_texts/English/MAT.xml
- DistFiles/reference_texts/English/MRK.xml
- DistFiles/reference_texts/English/PHP.xml
- DistFiles/reference_texts/English/REV.xml
- DistFiles/reference_texts/English/ROM.xml
- DistFiles/reference_texts/English/TIT.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/163)
> Clean up section headings and extraneous [1]s (PG-698)

- Glyssen/Project.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/164)
> PG-706: Upgraded projects not fully initialized

- Glyssen/ReferenceText.cs
- GlyssenTests/ReferenceTextTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/165)
> Fix bug causing some reference lines to get dropped altogether (PG-711)

- DevTools/DevTools.csproj
- DevTools/Program.cs
- DevTools/ReferenceTextUtility.cs
- DevTools/packages.config
- DistFiles/reference_texts/English/1CO.xml
- DistFiles/reference_texts/English/1JN.xml
- DistFiles/reference_texts/English/1PE.xml
- DistFiles/reference_texts/English/1TH.xml
- DistFiles/reference_texts/English/2CO.xml
- DistFiles/reference_texts/English/2PE.xml
- DistFiles/reference_texts/English/2TH.xml
- DistFiles/reference_texts/English/2TI.xml
- DistFiles/reference_texts/English/ACT.xml
- DistFiles/reference_texts/English/COL.xml
- DistFiles/reference_texts/English/EPH.xml
- DistFiles/reference_texts/English/GAL.xml
- DistFiles/reference_texts/English/HEB.xml
- DistFiles/reference_texts/English/JAS.xml
- DistFiles/reference_texts/English/JHN.xml
- DistFiles/reference_texts/English/JUD.xml
- DistFiles/reference_texts/English/LUK.xml
- DistFiles/reference_texts/English/MAT.xml
- DistFiles/reference_texts/English/MRK.xml
- DistFiles/reference_texts/English/PHP.xml
- DistFiles/reference_texts/English/REV.xml
- DistFiles/reference_texts/English/ROM.xml
- DistFiles/reference_texts/English/TIT.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/166)
> Ensure English reference text is broken in the correct places (PG-698)

- DistFiles/reference_texts/English/EPH.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/167)
> Fixed missing verse number for Ephesians 4:27 (PG-698)

- DevTools/DevTools.csproj
- DevTools/Program.cs
- DevTools/ReferenceTextUtility.cs
- Glyssen/Block.cs
- Glyssen/ReferenceText.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/171)
> PG-722: Dev tool to link reference texts to English

- DistFiles/reference_texts/Azeri/REV.xml
- DistFiles/reference_texts/French/REV.xml
- DistFiles/reference_texts/Indonesian/REV.xml
- DistFiles/reference_texts/Portuguese/REV.xml
- DistFiles/reference_texts/Russian/REV.xml
- DistFiles/reference_texts/Spanish/REV.xml
- DistFiles/reference_texts/TokPisin/REV.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/172)
> Correction to verse number in Rev 18:17 (PG-713)

- Glyssen/Bundle/GlyssenDblTextMetadata.cs
- Glyssen/Dialogs/ProjectSettingsDlg.Designer.cs
- Glyssen/Dialogs/ProjectSettingsDlg.cs
- Glyssen/Project.cs
- Glyssen/ProjectExporter.cs
- GlyssenTests/Bundle/GlyssenDblTextMetadataTests.cs
- GlyssenTests/ProjectExportTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/173)
> UI changes for selection of reference text

- DevTools/AnnotationExtractor.cs
- DevTools/ReferenceTextUtility.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/175)
> More changes to the dev tool for generating reference texts from the FCBH director guide

- Glyssen/Dialogs/RolesForVoiceActorsSaveAsDialog.cs
- Glyssen/ProjectExporter.cs
Also only notify user for several errors rather than show yellow screen.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/176)
> Include annotations in export

- DevTools/BiblicalTerms/Processor.cs
- DevTools/CharacterDetailProcessing.cs
- DevTools/TermTranslator/Processor.cs
- DistFiles/localization/Glyssen.en.tmx
- DistFiles/localization/Glyssen.es.tmx
- DistFiles/localization/Glyssen.fr.tmx
- DistFiles/localization/Glyssen.pt.tmx
- DistFiles/localization/Glyssen.zh-hans.tmx
- DistFiles/localization/Glyssen.zh-hant.tmx
- Glyssen/Dialogs/RolesForVoiceActorsSaveAsDialog.cs
- Glyssen/ProjectExporter.cs
- Glyssen/Resources/CharacterDetail.txt
- Glyssen/Resources/CharacterVerse.txt
Also update DevTool paths and tmx files for character IDs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/177)
> A few minor updates to the control file

- DistFiles/reference_texts/Azeri/JUD.xml
- Glyssen/Dialogs/ProjectSettingsDlg.cs
- Glyssen/Project.cs
- Glyssen/ProjectBase.cs
- Glyssen/ProjectExporter.cs
- Glyssen/ReferenceText.cs
- GlyssenTests/ProjectExportTests.cs
- GlyssenTests/ReferenceTextTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/182)
> PG-724: When exporting, include reference text column(s)

- DevTools/ReferenceTextUtility.cs
- DistFiles/reference_texts/Azeri/2JN.xml
- DistFiles/reference_texts/Azeri/3JN.xml
This only affects single-chapter books in Azeri.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/184)
> PG-725: Minor improvement to distinguish between book name and chapter label

- Glyssen/BookScript.cs
- GlyssenTests/BookScriptTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/185)
> PG-736: Handled splitting after a verse bridge that is split across blocks.

- Glyssen/Project.cs
- Glyssen/ProjectBase.cs
- Glyssen/ReferenceText.cs
- GlyssenTests/ProjectExportTests.cs
- GlyssenTests/ReferenceTextTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/190)
> PG-699: Prevented accidental matching of a single-verse vernacular block to a reference text block that includes part of the following verse

- DevTools/ReferenceTextUtility.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/193)
> Enhance dev tool to allow for the creation of a Glyssen-to-FCBH character mapping

- Glyssen/Resources/CharacterDetail.txt
- Glyssen/Resources/CharacterVerse.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/195)
> Two control file additions based on textual or interpretational differences

- Glyssen/BookScript.cs
- GlyssenTests/ReferenceTextTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/197)
> PG-744: Fixed crash splitting reference text verses with sound effects.

- DevTools/ReferenceTextUtility.cs
- Glyssen/Block.cs
- Glyssen/BlockElement.cs
- Glyssen/ProjectExporter.cs
- GlyssenTests/ProjectExportTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/199)
> PG-738: Mashed annotations together with the text instead of using separate rows.

- Glyssen/BookScript.cs
- Glyssen/ReferenceText.cs
- GlyssenTests/BookScriptTests.cs
Working on actual fix
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/200)
> Quick stop-gap to prevent crash during export (PG-746)

- DevTools/DevTools.csproj
- DevTools/ReferenceTextUtility.cs
- DistFiles/reference_texts/Azeri/LUK.xml
- DistFiles/reference_texts/French/2CO.xml
- DistFiles/reference_texts/French/LUK.xml
- DistFiles/reference_texts/Indonesian/2CO.xml
- DistFiles/reference_texts/Indonesian/ACT.xml
- DistFiles/reference_texts/Indonesian/JHN.xml
- DistFiles/reference_texts/Indonesian/LUK.xml
- DistFiles/reference_texts/Indonesian/MAT.xml
- DistFiles/reference_texts/Indonesian/MRK.xml
- DistFiles/reference_texts/Indonesian/ROM.xml
- DistFiles/reference_texts/Portuguese/2CO.xml
- DistFiles/reference_texts/Portuguese/LUK.xml
- DistFiles/reference_texts/Russian/LUK.xml
- DistFiles/reference_texts/Russian/MRK.xml
- DistFiles/reference_texts/Spanish/LUK.xml
- DistFiles/reference_texts/TokPisin/ACT.xml
- DistFiles/reference_texts/TokPisin/GAL.xml
- DistFiles/reference_texts/TokPisin/HEB.xml
- DistFiles/reference_texts/TokPisin/JAS.xml
- DistFiles/reference_texts/TokPisin/JHN.xml
- DistFiles/reference_texts/TokPisin/LUK.xml
- DistFiles/reference_texts/TokPisin/MAT.xml
- DistFiles/reference_texts/TokPisin/MRK.xml
- DistFiles/reference_texts/TokPisin/REV.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/201)
> Update ReferenceTextUtility and correct more problems in reference text data (PG-746)

- Glyssen/Quote/QuoteParser.cs
- GlyssenTests/Quote/QuoteParserTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/207)
> PG-751: Fixed problem with "Is probably an apostrophe" logic.

- Glyssen/Dialogs/CastSizePlanningViewModel.cs
We hope this will enable us to get better info if the character detail lookup ever fails again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/208)
> PG-709: Minor improvement to error handling

- Glyssen/Resources/CharacterVerse.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/209)
> Minor fix to remove spurious line from control file for Lev 23:44

- Glyssen/Glyssen.csproj
- Glyssen/MainForm.Designer.cs
- Glyssen/MainForm.cs
- Glyssen/MainForm.resx
- Glyssen/Program.cs
- Glyssen/ProjectBase.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/210)
> PG-536: Add export and import functionality

- Glyssen/Dialogs/AssignCharacterDlg.cs
- Glyssen/Dialogs/AssignCharacterViewModel.cs
- Glyssen/Dialogs/SplitBlockDlg.cs
- GlyssenTests/Dialogs/AssignCharacterViewModelTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/211)
> PG-754: Error if a character has 2 deliveries in same verse

- Glyssen/ControlAnnotations.cs
- Glyssen/ProjectExporter.cs
- Glyssen/ReferenceText.cs
- GlyssenTests/ProjectExportTests.cs
- GlyssenTests/ReferenceTextTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/212)
> PG-746: Match leading and trailing blocks to reference text for verses that don't match completely

- Glyssen/ProjectExporter.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/213)
> PG-730: Colorize annotations in Excel file output

- Glyssen/MainForm.cs
- Glyssen/ProjectExporter.cs
Due to the localized character ID column that is inserted
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/214)
> PG-759: Crash viewing recording script, non-English UI

- Glyssen/Dialogs/ProjectSettingsDlg.Designer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/219)
> PG-757: Improve wording in UI for Reference Text selection

- ControlDataIntegrityTests/Properties/AssemblyInfo.cs
- DevTools/Properties/AssemblyInfo.cs
- DevTools/TermTranslator/Processor.cs
- Glyssen/Dialogs/ProjectSettingsDlg.Designer.cs
- Glyssen/Properties/AssemblyInfo.cs
- GlyssenTests/Properties/AssemblyInfo.cs
- build/Glyssen.proj
- build/TestInstallerBuild.bat
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/222)
> Update to version 0.17 And merge in changes from 0.11

- Glyssen/Block.cs
- GlyssenTests/BlockTests.cs
- GlyssenTests/BookScriptTests.cs
- GlyssenTests/ProjectExportTests.cs
- GlyssenTests/Quote/QuoteParserTests.cs
- GlyssenTests/ReferenceTextTests.cs
- GlyssenTests/UsxParserTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/228)
> PG-790: Use curly braces instead of square brackets for verse numbers.

- Glyssen/Block.cs
- GlyssenTests/BlockTests.cs
- GlyssenTests/BookScriptTests.cs
- GlyssenTests/ProjectExportTests.cs
- GlyssenTests/Quote/QuoteParserTests.cs
- GlyssenTests/ReferenceTextTests.cs
- GlyssenTests/UsxParserTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/230)
> Merge pg790 from011

- Glyssen/Block.cs
- Glyssen/Quote/QuoteParser.cs
- GlyssenTests/BlockTests.cs
- GlyssenTests/BookScriptTests.cs
- GlyssenTests/ProjectExportTests.cs
- GlyssenTests/Quote/QuoteParserTests.cs
- GlyssenTests/ReferenceTextTests.cs
- GlyssenTests/UsxParserTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/229)
> PG-790: Use curly braces instead of brackets to mark verse numbers

- Glyssen/Resources/CharacterDetail.txt
- Glyssen/Resources/CharacterVerse.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/204)
> Additions to control file after looking at 'Unknown' characters in Gullah NT

- Glyssen/ProjectExporter.cs
- Glyssen/ReferenceText.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/226)
> PG-788: Font applied in settings should be applied in the export file

- DevTools/ReferenceTextUtility.cs
- Glyssen/Block.cs
- Glyssen/Bundle/GlyssenDblTextMetadata.cs
- Glyssen/Character/CharacterDetail.cs
- Glyssen/Character/CharacterDetailData.cs
- Glyssen/Character/CharacterVerseData.cs
- Glyssen/Dialogs/AssignCharacterDlg.cs
- Glyssen/Dialogs/AssignCharacterViewModel.cs
- Glyssen/Dialogs/BlockNavigatorViewModel.cs
- Glyssen/Dialogs/CastSizePlanningViewModel.cs
- Glyssen/Dialogs/ProjectSettingsDlg.Designer.cs
- Glyssen/Dialogs/ProjectSettingsDlg.cs
- Glyssen/Dialogs/VoiceActorAssignmentViewModel.cs
- Glyssen/Quote/QuoteParser.cs
- Glyssen/ReferenceText.cs
- Glyssen/Rules/CharacterGroupGenerator.cs
- Glyssen/Rules/Proximity.cs
- GlyssenTests/ProjectTests.cs
- GlyssenTests/Rules/CharacterGroupGeneratorTests.cs
- GlyssenTests/Rules/CharacterGroupsAdjusterTests.cs
- GlyssenTests/Rules/ProximityTests.cs
- GlyssenTests/Rules/TrialGroupConfigurationTests.cs
Continuation of work started by Phil Hopper
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/231)
> PG-692: Options for extra-biblical parts

- Glyssen/Dialogs/AssignCharacterDlg.cs
- Glyssen/Dialogs/AssignCharacterViewModel.cs
Also, prompt user to close dialog when all assignments have been made.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/239)
> Made progress status update when applying block matchups

- Glyssen/Controls/ScriptBlocksGridView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/241)
> Re-made change that got lost in previous commit

- Glyssen/Controls/ScriptBlocksGridView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/245)
> Added debug code to try to figure out what is causing PG-810 and to prevent fatal crash.

- Glyssen/ProjectExporter.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/248)
> PG-815: Fixed crash when opening recording script with when UI is not English

- Glyssen/ProjectExporter.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/250)
> Merge PG-815: Fixed crash when opening recording script when UI is not English

- DevTools/ReferenceTextUtility.cs
- Glyssen/Bundle/GlyssenDblTextMetadata.cs
- Glyssen/Controls/VoiceActorInformationGrid.resx
- Glyssen/Dialogs/ProjectSettingsDlg.cs
- Glyssen/MainForm.cs
- Glyssen/Project.cs
- Glyssen/ProjectExporter.cs
- Glyssen/ReferenceTextIdentifier.cs
- GlyssenTests/ReferenceTextIdentifierTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/252)
> PG-818: Prevent crash caused by missing custom reference text

- DistFiles/localization/Glyssen.en.tmx
- DistFiles/localization/Glyssen.es.tmx
- DistFiles/localization/Glyssen.fr.tmx
- DistFiles/localization/Glyssen.pt.tmx
- DistFiles/localization/Glyssen.zh-hant.tmx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/262)
> Enhancements to localizations for a couple character IDs

- Installer/Installer.wxs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/264)
> Removed spurious Component element

- Installer/Installer.wxs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/266)
> Added missing closer for Component element

- Glyssen/ProjectExporter.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/270)
> Reverted bad change that breaks export of master script.

- Glyssen/BlockMatchup.cs
- Glyssen/BlockNavigator.cs
- Glyssen/Dialogs/AssignCharacterDlg.cs
- Glyssen/Dialogs/BlockNavigatorViewModel.cs
- Glyssen/Dialogs/VoiceActorAssignmentDlg.cs
- Glyssen/ProjectDataMigrator.cs
- Glyssen/ProjectExporter.cs
- GlyssenTests/Dialogs/AssignCharacterViewModelTests.cs
- GlyssenTests/ProjectExportTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/271)
> Exclude Delivery if exporting single-voice narrator script

- Glyssen/Controls/ScriptBlocksGridView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/273)
> PG-839: Prevented scrolling as a side-effect of selecting a row from changing the selection

- Glyssen/Block.cs
- Glyssen/BlockMatchup.cs
- Glyssen/Dialogs/AssignCharacterDlg.cs
- GlyssenTests/BlockMatchupTests.cs
Also fixed a crashing bug that can occur if user passes mouse over the Move Up or Move Down button before grid is fully populated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/281)
> PG-838: Made the Insert "He said" button work in a cell that contains only a verse number.

- Glyssen/Block.cs
- Glyssen/Resources/CharacterDetail.txt
- Glyssen/Resources/CharacterVerse.txt
- GlyssenTests/BlockMatchupTests.cs
- GlyssenTests/BlockTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/282)
> PG-837: Made Move Down keep the leading verse number in original cell in the secondary reference language

- Glyssen/Block.cs
- Glyssen/BlockMatchup.cs
- Glyssen/BookScript.cs
- Glyssen/Controls/ScriptBlocksGridView.cs
- Glyssen/Controls/ScriptBlocksViewer.Designer.cs
- Glyssen/Dialogs/AssignCharacterDlg.cs
- Glyssen/Dialogs/AssignCharacterViewModel.cs
- Glyssen/Dialogs/BlockNavigatorViewModel.cs
- Glyssen/PortionScript.cs
- GlyssenTests/BookScriptTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/284)
> PG-844, PG-846, PG-847 and split improvements

- Glyssen/Resources/CharacterVerse.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/285)
> The possible indirect speech that begins in Mrk 3:14 could continue into verse 15.

- Glyssen/Resources/CharacterDetail.txt
- Glyssen/Resources/CharacterVerse.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/287)
> Added potential indirect speech for MRK 15:3 & updated references in CharacterDetail.txt

- Glyssen/ProjectExporter.cs
- GlyssenTests/ProjectExportTests.cs
This is not ideal, but it avoids exceptions that cause those files to fail to export. PG-849 is a follow-on task to get everything working correctly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/288)
> PG-855: Do not attempt to colorize annotations for actor and book scripts

- Glyssen/Dialogs/AssignCharacterDlg.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/289)
> PG-857: Fixed crash trying to make invisible cell current.

- Glyssen/Character/CharacterGroup.cs
- Glyssen/Controls/CastSizePlanningOptions.cs
- Glyssen/Dialogs/CastSizePlanningDlg.Designer.cs
- Glyssen/Dialogs/VoiceActorAssignmentDlg.cs
- Glyssen/Dialogs/VoiceActorAssignmentUndoAction.cs
- Glyssen/Dialogs/VoiceActorAssignmentViewModel.cs
- Glyssen/MainForm.cs
- Glyssen/Project.cs
- GlyssenTests/Dialogs/VoiceActorAssignmentUndoActionTests.cs
- GlyssenTests/Dialogs/VoiceActorAssignmentViewModelTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/291)
> PG-867: Enable "Match Voice Actor List" after user adds voice actors.

- Glyssen/MainForm.cs
- Glyssen/Project.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/292)
> PG-870: Try to prevent and recover from empty LDML files.

- Glyssen/Project.cs
Main improvement was adding the option to attempt to recover from existing backup when reading. Also, added a bunch of Logger.WriteError commands to try to make it easier to debug Glyssen.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/293)
> PG-870: More enhancements to improve robustness of LDML file failover logic

- ControlDataIntegrityTests/Properties/AssemblyInfo.cs
- DevTools/Properties/AssemblyInfo.cs
- DevTools/TermTranslator/Processor.cs
- GlyssenTests/Properties/AssemblyInfo.cs
- build/Glyssen.proj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/294)
> Incremented "master" version number to 0.18

- Glyssen/ProjectExporter.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/296)
> PG-869: Trying a different approach to hyperlinks to see if they will work in Excel 2007

- Glyssen/Dialogs/BlockNavigatorViewModel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/297)
> PG-844: Prevent trying to create a block matchup starting with a non-Scripture block.

- Glyssen/Controls/ScriptBlocksViewer.cs
- Glyssen/Dialogs/AssignCharacterDlg.Designer.cs
- Glyssen/Dialogs/AssignCharacterDlg.cs
- Glyssen/Dialogs/BlockNavigatorViewModel.cs
- GlyssenTests/Dialogs/BlockNavigatorViewModelTests.cs
but prevent changing character or delivery.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/299)
> PG-874 Enable rainbow mode to show matchup for blocks that are not at the start of a quote

- Glyssen/MainForm.cs
Also added warnings about implications of importing/exporting a project with a (potentially unavailable) custom reference text.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/300)
> PG-871: Prevented crash from opening Identify Speaking Parts with missing reference text

- Glyssen/BlockMatchup.cs
- Glyssen/Controls/ScriptBlocksViewer.cs
- Glyssen/Dialogs/AssignCharacterDlg.Designer.cs
- Glyssen/Dialogs/AssignCharacterDlg.cs
- Glyssen/Dialogs/BlockNavigatorViewModel.cs
- Glyssen/MainForm.cs
- Glyssen/ProjectExporter.cs
- GlyssenTests/Dialogs/BlockNavigatorViewModelTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/302)
> Merge of latest changes from 0.17 branch

- Glyssen/BookScript.cs
- GlyssenTests/BookScriptTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/304)
> PG-829: Prevented combining words when joining adjacent blocks for export.

- Glyssen/Dialogs/AssignCharacterDlg.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/306)
> Prevent attempting to correct delivery by setting null to "normal"

- Glyssen/BlockMatchup.cs
- GlyssenTests/BlockMatchupTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/307)
> PG-845: Deal with verses that are repeated due to alternate endings.

- Glyssen/Dialogs/PercentageOfExpectedQuotesFoundTooLowDlg.Designer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/310)
> PG-881: attempted to fix a problem with 125% font size

- Glyssen/BiblicalAuthors.cs
- Glyssen/Character/CharacterGroup.cs
- Glyssen/Resources/BiblicalAuthors.txt
- Glyssen/Rules/AuthorStats.cs
- Glyssen/Rules/CharacterGroupGenerator.cs
- GlyssenTests/Dialogs/CastSizePlanningViewModelTests.cs
- GlyssenTests/GlyssenTests.csproj
- GlyssenTests/Rules/AuthorStatsTests.cs
- GlyssenTests/Rules/CharacterGroupGeneratorTests.cs
- GlyssenTests/Rules/TrialGroupConfigurationTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/309)
> PG-667: Group author characters with narration roles when "Narration by Author" is selected.

- Glyssen/Dialogs/BlockNavigatorViewModel.cs
- GlyssenTests/Dialogs/BlockNavigatorViewModelTests.cs
- GlyssenTests/GlyssenTests.csproj
- GlyssenTests/Properties/Resources.Designer.cs
- GlyssenTests/Properties/Resources.resx
- GlyssenTests/Resources/TestJHN.xml
- GlyssenTests/TestProject.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/311)
> PG-879: Fixed argument out of range exception caused by applying matchup to blocks not in filter

- Glyssen/ProjectExporter.cs
Also set Internal title (in Excel file) based on project name and Audio Stock Number
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/312)
> PG-779: Added stock number (if present) to script file name

- Glyssen/Project.cs
- Glyssen/Resources/CharacterDetail.txt
- Glyssen/Resources/CharacterVerse.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/318)
> PG-806: Added some new entries to CharacterVerse control file for Isaiah.

- Glyssen/BlockMatchup.cs
- Glyssen/BlockNavigator.cs
- Glyssen/Controls/BlockProgressBar.cs
- Glyssen/Dialogs/AssignCharacterDlg.Designer.cs
- Glyssen/Dialogs/AssignCharacterDlg.cs
- Glyssen/Dialogs/AssignCharacterViewModel.cs
- Glyssen/Dialogs/BlockNavigatorViewModel.cs
- Glyssen/Project.cs
- Glyssen/ReferenceText.cs
- GlyssenTests/Dialogs/AssignCharacterViewModelTests.cs
- GlyssenTests/Dialogs/BlockNavigatorViewModelTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/325)
> PG-888, PG-865, PG-716, PG-878: Improved task-based workflow for aligning blocks to the reference text

- Glyssen/Dialogs/BlockNavigatorViewModel.cs
- GlyssenTests/Dialogs/AssignCharacterViewModelTests.cs
- GlyssenTests/Dialogs/BlockNavigatorViewModelTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/332)
> PG-912 Fixed 'Blocks not aligned' filter to exclude blocks that have been assigned and user-confirmed

- Glyssen/Dialogs/AssignCharacterDlg.Designer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/333)
> PG-920: Re-added call to m_dataGridReferenceText_CellPainting that was inadvertently reverted

- Glyssen/Analysis/ProjectAnalysis.cs
- Glyssen/Block.cs
- Glyssen/BlockMatchup.cs
- Glyssen/BlockNavigator.cs
- Glyssen/BookScript.cs
- Glyssen/Dialogs/AssignCharacterDlg.cs
- Glyssen/Dialogs/AssignCharacterViewModel.cs
- Glyssen/Dialogs/BlockNavigatorViewModel.cs
- Glyssen/MultiBlockQuote.cs
- Glyssen/PortionScript.cs
- Glyssen/ProjectDataMigrator.cs
- GlyssenTests/BlockMatchupTests.cs
- GlyssenTests/BookScriptTests.cs
- GlyssenTests/Dialogs/AssignCharacterViewModelTests.cs
- GlyssenTests/Dialogs/BlockNavigatorViewModelTests.cs
- GlyssenTests/GlyssenTests.csproj
- GlyssenTests/Properties/Resources.Designer.cs
- GlyssenTests/Properties/Resources.resx
- GlyssenTests/ReferenceTextTests.cs
- GlyssenTests/Resources/TestCharacterVerseOct2015.txt
- GlyssenTests/Resources/TestMATcuk.xml
- GlyssenTests/TestProject.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/334)
> PG-895: Fixed handling of quote continuation blocks when changing character in rainbow mode

- Glyssen/Dialogs/AssignCharacterDlg.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/335)
> Code cleanup: Removed unused HandleBlocksViewerSelectionChanged method.

- Glyssen/Project.cs
- GlyssenTests/ProjectTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/343)
> Merge from 0.17 into master again

- Glyssen/Dialogs/BlockNavigatorViewModel.cs
- GlyssenTests/Dialogs/BlockNavigatorViewModelTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/345)
> Merge PG-924 from 0.17 branch

- Glyssen/App.config
- Glyssen/Block.cs
- Glyssen/BlockElement.cs
- Glyssen/BookScript.cs
- Glyssen/PortionScript.cs
- Glyssen/Properties/Settings.Designer.cs
- Glyssen/Properties/Settings.settings
- Glyssen/Quote/QuoteParser.cs
- Glyssen/ReferenceText.cs
- Glyssen/UsxParser.cs
- GlyssenTests/BlockMatchupTests.cs
- GlyssenTests/BlockTests.cs
- GlyssenTests/BookScriptTests.cs
- GlyssenTests/ReferenceTextTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/353)
> PG-933: Join adjacent blocks by same speaker during export under special circumstances

- Glyssen/Rules/CharacterGroupGenerator.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/354)
> PG-952: Prevented crash when attempted to add a book's author to a group when the author has no speaking parts.

- Glyssen/Project.cs
so we can see where the problem in the data is. Not sure how this can happen.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/358)
> Added check for null character ID when calculating stats

- Glyssen/BlockMatchup.cs
- Glyssen/Dialogs/AssignCharacterDlg.cs
- GlyssenTests/BlockMatchupTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/359)
> PG-951: Ask user whether to fix places in the reference text that end with a verse number

- Glyssen/Utilities/FormWithPersistedSettings.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/362)
> PG-948: Fixed problem trying to restore ISP dialog to normal size after it was closed and reopened maximized.

- ControlDataIntegrityTests/CharacterVerseDataTests.cs
- DistFiles/reference_texts/English/MAT.xml
- DistFiles/reference_texts/English/MRK.xml
- DistFiles/reference_texts/Russian/MAT.xml
- DistFiles/reference_texts/Russian/MRK.xml
- Glyssen/App.config
- Glyssen/Block.cs
- Glyssen/Character/CharacterVerse.cs
- Glyssen/PortionScript.cs
- Glyssen/Properties/Settings.Designer.cs
- Glyssen/Properties/Settings.settings
- Glyssen/Quote/QuoteParser.cs
- Glyssen/Resources/CharacterVerse.txt
- GlyssenTests/Character/CharacterAssignerTests.cs
- GlyssenTests/Quote/QuoteParserTests.cs
- GlyssenTests/Resources/TestCharacterVerse.txt
- GlyssenTests/Resources/TestCharacterVerseOct2015.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/363)
> PG-781: Made quote parser handle possible narrator interruptions in quoted direct speech.

- Glyssen/ProjectExporter.cs
- GlyssenTests/ProjectExportTests.cs
per FCBH request
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/364)
> PG-747: Changed exporter to put only leading verse number of a verse bridge in Verse column

- Glyssen/Dialogs/AssignCharacterDlg.Designer.cs
- Glyssen/Dialogs/AssignCharacterDlg.cs
- Glyssen/Dialogs/AssignCharacterDlg.resx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/365)
> PG-821: Implemented "Split Text" command to make it easier to distribute reference text into neighboring empty cells.

- Glyssen/Dialogs/AssignCharacterDlg.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/366)
> Fixed error in formatting message

- Glyssen/Dialogs/AssignCharacterDlg.Designer.cs
- Glyssen/Dialogs/AssignCharacterDlg.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/367)
> PG-953: Added additional menu items to ISP reference text context menu

- Glyssen/Dialogs/BlockNavigatorViewModel.cs
- GlyssenTests/Dialogs/BlockNavigatorViewModelTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/368)
> PG-956: Fixed crash when clicking in section head block in script blocks pane

- Glyssen/Dialogs/AddCharacterDlg.Designer.cs
- Glyssen/Dialogs/AddCharacterDlg.cs
- Glyssen/Dialogs/AddCharacterDlg.resx
- Glyssen/Dialogs/AssignCharacterDlg.Designer.cs
- Glyssen/Dialogs/AssignCharacterDlg.cs
- Glyssen/Dialogs/AssignCharacterViewModel.cs
- Glyssen/Glyssen.csproj
This also fixes a bug in the code for enabling context menu items.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/370)
> PG-893: Added context menu to allow adding character/delivery in rainbow mode.

- .gitignore
- DistFiles/.guidsForInstaller.xml
- DistFiles/ReleaseNotes.md
- Glyssen/Glyssen.csproj
- Glyssen/MainForm.Designer.cs
- Glyssen/MainForm.cs
- Installer/Installer.wxs
- Installer/appcast.xml
- build/Glyssen.proj
- build/buildUpdate.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/371)
> PG-937: Made Glyssen able to check for updates

- Installer/Installer.wxs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/372)
> PG-937: Fixed Installer problem

- Installer/Installer.wxs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/374)
> PG-937: Added ComponentRef for MarkdownDeep.dll

- Glyssen/App.config
- Glyssen/Dialogs/AssignCharacterDlg.Designer.cs
- Glyssen/Dialogs/AssignCharacterDlg.cs
- Glyssen/Properties/Settings.Designer.cs
- Glyssen/Properties/Settings.settings
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/375)
> PG-931: Removed Formatted Scripture view

- Glyssen/App.config
- Glyssen/Dialogs/AssignCharacterDlg.Designer.cs
- Glyssen/Dialogs/AssignCharacterDlg.cs
- Glyssen/Properties/Settings.Designer.cs
- Glyssen/Properties/Settings.settings
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/376)
> PG-756: Added (optional) ability to have Glyssen interpret double-clicks as equivalent to pressing the Assign Character button.

- Glyssen/Dialogs/VoiceActorAssignmentDlg.Designer.cs
- Glyssen/Dialogs/VoiceActorInformationDlg.Designer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/377)
> PG-642: Made Help buttons invisible since we don't have a Help system.

- Glyssen/Resources/CharacterDetail.txt
- Glyssen/Resources/CharacterVerse.txt
Also coalesced some of the "nations" characters.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/378)
> PG-693: Changed all "saying" characters to Quotation or Hypothetical.

- DistFiles/localization/Glyssen.es.tmx
- Glyssen/Analysis/ProjectAnalysis.cs
- Glyssen/Controls/BlockProgressBar.cs
- Glyssen/Dialogs/VoiceActorAssignmentDlg.Designer.cs
- Glyssen/Dialogs/VoiceActorAssignmentDlg.cs
- Glyssen/MainForm.Designer.cs
- Glyssen/MainForm.cs
- Glyssen/Utilities/MathUtilities.cs
- GlyssenTests/Utilities/MathUtilitiesTests.cs
PG-610: Solved crashing bug from clicking Find Next too fast.
PG-963: Fixed confusing UI caused by rounding display of percentages up to 100%
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/379)
> PG-777: Improved UI and user interaction when finding characters.

- Glyssen/Controls/ControlExtensions.cs
- Glyssen/Controls/ScriptBlocksViewer.cs
- Glyssen/Dialogs/AssignCharacterDlg.cs
- Glyssen/Dialogs/QuotationMarksDlg.cs
- Reference Text Utility/OutputForm.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/384)
> Switched to using the SafeInvoke in libpalaso

- Glyssen/Dialogs/ExportToRecordingToolDlg.Designer.cs
- Glyssen/Dialogs/ExportToRecordingToolDlg.cs
- Glyssen/Dialogs/ExportToRecordingToolDlg.resx
- Glyssen/Dialogs/ViewScriptDlg.Designer.cs
- Glyssen/Dialogs/ViewScriptDlg.cs
- Glyssen/Glyssen.csproj
- Glyssen/ProjectExporter.cs
- Glyssen/ScriptExporter.cs
- GlyssenShared/Script/GlyssenScript.cs
- GlyssenTests/GlyssenTests.csproj
- GlyssenTests/ScriptExporterTests.cs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/393)
> Add new dialog for exporting to HearThis

- Glyssen/ScriptExporter.cs
- GlyssenShared/Script/GlyssenScript.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/396)
> Improve XML structure and naming

- Reference Text Utility/Installer/RTUInstaller.wixproj
- Reference Text Utility/Installer/RTUInstaller.wxs
- build/TestRTUInstallerBuild.bat
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/397)
> Upgraded Reference Text Utility Installer to 1.0.2, to correspond with Glyssen 1.0

- Glyssen/Dialogs/AssignCharacterDlg.cs
- Glyssen/Dialogs/BlockNavigatorViewModel.cs
- Glyssen/Resources/CharacterVerse.txt
Also, made a few minor improvements to the CharacterVerse data for Rev 18
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/398)
> PG-1035: Enhanced debugging info to try to track down problem.

- Glyssen/Dialogs/VoiceActorAssignmentViewModel.cs
- Glyssen/Rules/CharacterGroupGenerator.cs
- Glyssen/Rules/Proximity.cs
- Glyssen/ScriptExporter.cs
- GlyssenShared/Script/GlyssenScript.cs
1) Added an attribute to the glyssenscript to store the recording project name.
2) Put info into log file that indicates proximity when groups are generated/modified.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/399)
> Two small enhancements (for HT scripts & for Duane)

- GlyssenShared/Bundle/GlyssenDblTextMetadataBase.cs
- GlyssenShared/Script/GlyssenScript.cs
- GlyssenTests/Bundle/GlyssenDblTextMetadataTests.cs
This is specific to elements and attributes added for HearThis export
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/402)
> Use lowerCamelCase for xml elements and attributes

- Glyssen/Dialogs/GenerateGroupsProgressDialog.cs
- Glyssen/Dialogs/ProgressDialogWithAcknowledgement.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/404)
> PG-1049: Prevented crash when new voice actor list cannot fulfill project narration requirements.

- Glyssen/Character/CharacterGroup.cs
- Glyssen/Dialogs/ProgressDialogWithAcknowledgement.cs
- Glyssen/Rules/CharacterGroupGenerator.cs
- Glyssen/VoiceActor/VoiceActor.cs
- GlyssenTests/Rules/CharacterGroupGeneratorTests.cs
- GlyssenTests/VoiceActor/VoiceActorTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/405)
> PG-1055: Improve character group generation to avoid mixing genders

- Glyssen/Block.cs
- Glyssen/Dialogs/VoiceActorAssignmentViewModel.cs
- Glyssen/Project.cs
- Glyssen/ProjectExporter.cs
- Glyssen/ReferenceText.cs
- Glyssen/Rules/CharacterGroupGenerator.cs
- Glyssen/Rules/Proximity.cs
- GlyssenTests/BlockTests.cs
- GlyssenTests/Rules/CharacterGroupGeneratorTests.cs
- GlyssenTests/Rules/ProximityTests.cs
- GlyssenTests/Rules/TrialGroupConfigurationTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/406)
> Rework proximity calculation to use verses rather than blocks (PG-454)

- DistFiles/reference_texts/English/REV.xml
- DistFiles/reference_texts/Russian/REV.xml
- Glyssen/Character/CharacterGroup.cs
- Glyssen/Resources/CharacterDetail.txt
- Glyssen/Resources/CharacterVerse.txt
- GlyssenTests/ProjectDataMigratorTests.cs
Also fixes a problem with data migration and the way character groups
handle keystrokes per character
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/411)
> Improve four living creatures to use 4 actors instead of 5

- Glyssen/Rules/CharacterGroupGenerator.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/413)
> Added logic to prevent adult male roles being assigned to child actors.

- Glyssen/Resources/CharacterVerse.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/415)
> Add indirect quote in Matt 2:22

- Glyssen/Dialogs/AssignCharacterDlg.cs
Tom and I worked on this together. No review necessary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/417)
> Set character ID and delivery for all quote-continuing blocks in rainbow matchup

- Glyssen/BookBlockIndices.cs
- Glyssen/Dialogs/AssignCharacterDlg.cs
- Glyssen/Dialogs/AssignCharacterViewModel.cs
- Glyssen/Dialogs/BlockNavigatorViewModel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/420)
> Correct automatic selection of delivery upon character change (PG-1072)

- Glyssen/Dialogs/BlockNavigatorViewModel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/422)
> If all fails and we are about to throw an exception, reset state and try again (PG-1078)

- Glyssen/Resources/CharacterDetail.txt
- Glyssen/Resources/CharacterVerse.txt
speaking in ACT 5:24, and Herodias as possible indirect speaker in MAT 14:8
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/423)
> Added high priest (as default) to the list of possible characters

- Glyssen/Character/CharacterVerseData.cs
- Glyssen/PortionScript.cs
- Glyssen/ProjectDataMigrator.cs
- Glyssen/Quote/QuoteParser.cs
- Glyssen/Resources/CharacterVerse.txt
- GlyssenTests/BookScriptTests.cs
- GlyssenTests/ProjectDataMigratorTests.cs
- GlyssenTests/Quote/QuoteParserTests.cs
- GlyssenTests/Resources/.editorconfig
- GlyssenTests/Resources/TestCharacterVerse.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/424)
> Fix multi-block quote settings for interruptions including a data migration (PG-1079)

- Glyssen/Controls/MenuButton.cs
- Glyssen/Dialogs/ViewScriptDlg.Designer.cs
- Glyssen/Dialogs/ViewScriptDlg.cs
- Glyssen/Dialogs/ViewScriptDlg.resx
- Glyssen/Glyssen.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/414)
> Move export script feature from File menu to Export button

- Glyssen/Rules/Proximity.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/425)
> Set minimum proximity down to 14 (to match FCBH calculation)

- DistFiles/reference_texts/English/MRK.xml
- DistFiles/reference_texts/Russian/MRK.xml
- RefTextDevUtilities/ReferenceTextUtility.cs
- Reference Text Utility/RefTextUtilityForm.cs
- Reference Text Utility/Reference Text Utility.csproj
- build/TestRTUInstallerBuild.bat
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/427)
> Re-sync director guide and reference text; fix crashing bug in Reference Text Utility

- Glyssen/ReferenceText.cs
- GlyssenTests/ReferenceTextTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/429)
> Fix single voice with section heading mid-verse (PG-1085)

- Glyssen/Bundle/GlyssenDblTextMetadata.cs
- GlyssenShared/Bundle/GlyssenDblTextMetadataBase.cs
- GlyssenShared/Script/GlyssenScript.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/432)
> Add AudioStockNumber to glyssenscript (PG-1074)

- Glyssen/UsxParser.cs
- GlyssenTests/UsxParserTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/433)
> Don't include character style attributes (PG-1084)

- Glyssen/ReferenceText.cs
- GlyssenTests/ReferenceTextTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/434)
> Handle mid-verse section headings correctly (PG-1086)

- Glyssen/Block.cs
- Glyssen/BlockSplitData.cs
- GlyssenTests/BlockTests.cs
- GlyssenTests/Dialogs/AssignCharacterViewModelTests.cs
- GlyssenTests/GlyssenTests.csproj
- GlyssenTests/Properties/Resources.Designer.cs
- GlyssenTests/Properties/Resources.resx
- GlyssenTests/Resources/TestOBAwithInterestingVerseNums.xml
- GlyssenTests/TestProject.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/435)
> Fix issues with splitting for verse bridges and verse segments (PG-1081)

- Glyssen/ProjectDataMigrator.cs
- Glyssen/Quote/QuoteParser.cs
- Glyssen/Resources/CharacterVerse.txt
- GlyssenTests/Quote/QuoteParserTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/436)
> Properly handle multiple interruptions in a multiblock quote (PG-1088)

- Glyssen/Dialogs/AssignCharacterViewModel.cs
- GlyssenTests/Dialogs/AssignCharacterViewModelTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/438)
> Ensure characterIds are set correctly after a split (PG-1089)

- Glyssen/BlockMatchup.cs
- Glyssen/BookScript.cs
- Glyssen/ControlAnnotations.cs
- Glyssen/Dialogs/ExportToRecordingToolDlg.cs
- Glyssen/Dialogs/ProjectSettingsViewModel.cs
- Glyssen/Glyssen.csproj
- Glyssen/PortionScript.cs
- Glyssen/ProjectExporter.cs
- Glyssen/Quote/QuoteParser.cs
- Glyssen/ScriptExporter.cs
- Glyssen/UsxParser.cs
- GlyssenShared/BlockElement.cs
- GlyssenShared/GlyssenShared.csproj
- GlyssenShared/Script/GlyssenScript.cs
- GlyssenTests/BlockElementTests.cs
- GlyssenTests/BookScriptTests.cs
- GlyssenTests/Character/CharacterAssignerTests.cs
- GlyssenTests/Dialogs/AssignCharacterViewModelTests.cs
- GlyssenTests/Dialogs/BlockNavigatorViewModelTests.cs
- GlyssenTests/ProjectDataMigratorTests.cs
- GlyssenTests/Quote/QuoteParserTests.cs
- GlyssenTests/ScriptExporterTests.cs
- GlyssenTests/UsxParserTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/439)
> Modify .glyssenscript to include block elements including verse numbers

- Glyssen/Block.cs
- Glyssen/BookScript.cs
- Glyssen/Character/CharacterAssigner.cs
- Glyssen/Character/CharacterVerseData.cs
- Glyssen/Character/CombinedCharacterVerseData.cs
- Glyssen/Character/ICharacterVerseInfo.cs
- Glyssen/Dialogs/AssignCharacterViewModel.cs
- Glyssen/Dialogs/BlockNavigatorViewModel.cs
- Glyssen/PortionScript.cs
- Glyssen/Project.cs
- Glyssen/Quote/QuoteSystemGuesser.cs
- GlyssenTests/BlockTests.cs
- GlyssenTests/Character/CharacterAssignerTests.cs
- GlyssenTests/Character/CharacterVerseDataTests.cs
- GlyssenTests/Character/ProjectCharacterVerseDataTests.cs
- GlyssenTests/Dialogs/BlockNavigatorViewModelTests.cs
- GlyssenTests/ProjectDataMigratorTests.cs
- GlyssenTests/Quote/QuoteParserTests.cs
- GlyssenTests/Quote/QuoteSystemGuesserTests.cs
- RefTextDevUtilities/ReferenceTextUtility.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/440)
> A couple slight code/performance improvements

- ControlDataIntegrityTests/CharacterDetailDataTests.cs
- ControlDataIntegrityTests/CharacterVerseDataTests.cs
- Glyssen/Character/CharacterVerse.cs
- Glyssen/Character/CharacterVerseData.cs
- Glyssen/Character/ControlCharacterVerseData.cs
- Glyssen/Resources/CharacterVerse.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/441)
> Treat hypothetical as narrator (PG-958)

- Glyssen/Resources/CharacterDetail.txt
- Glyssen/Resources/CharacterVerse.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/444)
> Add indirect speech for Jesus in MAT 4:21 (PG-1098)

- DevTools/CharacterDetailProcessing.cs
- Glyssen/Resources/CharacterDetail.txt
- Glyssen/Resources/CharacterVerse.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/445)
> Add several Indirect quotes to CharacterVerse.txt (PG-1100)

- Glyssen/ProjectExporter.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/446)
> Fix extraneous space in default export file name (PG-1102)

- Glyssen/Dialogs/ViewScriptDlg.cs
- Glyssen/Properties/Settings.Designer.cs
- Glyssen/Properties/Settings.settings
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/447)
> Persist form settings for View Script dialog (PG-731)

- Glyssen/Resources/CharacterDetail.txt
- Glyssen/Resources/CharacterVerse.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/450)
> Minor control file enhancements after talking to Mark Wright about Nitro discrepancies

- Glyssen/Controls/ScriptBlocksGridView.cs
- Glyssen/Dialogs/AssignCharacterDlg.cs
- Glyssen/Dialogs/AssignCharacterViewModel.cs
- Glyssen/Utilities/CustomColor.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/449)
> Color-code text by speaker type in rainbow mode (PG-1094)

- ControlDataIntegrityTests/CharacterDetailDataTests.cs
- ControlDataIntegrityTests/CharacterVerseDataTests.cs
- DevTools/CharacterDetailProcessing.cs
- DevTools/Program.cs
- Glyssen/Character/CharacterDetailData.cs
- Glyssen/Resources/CharacterDetail.txt
- Glyssen/Resources/CharacterVerse.txt
- GlyssenTests/Character/CharacterGroupTests.cs
- GlyssenTests/Dialogs/AssignCharacterViewModelTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/451)
> Allow user to add a character which is in the control file as hypothetical-only (PG-1104)

- Glyssen/Block.cs
- Glyssen/Dialogs/SplitBlockDlg.cs
- GlyssenTests/BlockTests.cs
- GlyssenTests/BookScriptTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/452)
> Allow user to split a block which has leading punctuation (PG-1107)

- Glyssen/Resources/CharacterVerse.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/457)
> Add possible Scripture quote for 1PE 4:8 (PG-1132)

- Glyssen/Resources/CharacterVerse.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/458)
> Add scripture as an option in 2TI 2:19 (PG-1132)

- Glyssen/Block.cs
- Glyssen/BlockMatchup.cs
- Glyssen/Dialogs/AssignCharacterViewModel.cs
- Glyssen/PortionScript.cs
- Glyssen/ProjectDataMigrator.cs
- Glyssen/Resources/CharacterVerse.txt
- GlyssenTests/ProjectDataMigratorTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/463)
> PG-1143: Fixed bug where splitting a block caused CharacterInScript to be overridden for narrator block

- ControlDataIntegrityTests/ControlDataIntegrityTests.csproj
- ControlDataIntegrityTests/packages.config
- DevTools/DevTools.csproj
- DevTools/packages.config
- Glyssen/Glyssen.csproj
- Glyssen/packages.config
- GlyssenTests/GlyssenTests.csproj
- GlyssenTests/packages.config
- RefTextDevUtilities/RefTextDevUtilities.csproj
- RefTextDevUtilities/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/464)
> Upgrade to ParatextData 8.1.7

- Glyssen/Utilities/CustomColor.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/471)
> PG-1094 - Improved readability of the rainbow color scheme

- DistFiles/localization/Glyssen.es.tmx
- Glyssen/Dialogs/ProjectSettingsDlg.Designer.cs
- Glyssen/Dialogs/ProjectSettingsDlg.cs
- Glyssen/Dialogs/SelectExistingProjectDlg.cs
- Glyssen/Project.cs
- Glyssen/Utilities/FileSystemUtils.cs
- GlyssenTests/GlyssenTests.csproj
- GlyssenTests/Utilities/FileSystemUtilsTests.cs
WIP: Just began dealing with issues of path length. Need to deal with long paths from bundles and Paratext as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/475)
> PG-1164: Prevented bad paths (from bundles, Paratext, and UI)

- Glyssen/Dialogs/AssignCharacterDlg.Designer.cs
- Glyssen/Dialogs/AssignCharacterDlg.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/481)
> PG-1103: Fix the black background on the drop down menu

- Glyssen/Block.cs
- Glyssen/BlockMatchup.cs
- Glyssen/BookScript.cs
- Glyssen/Dialogs/AssignCharacterDlg.cs
- Glyssen/Dialogs/AssignCharacterViewModel.cs
- GlyssenTests/BlockMatchupTests.cs
- GlyssenTests/Dialogs/AssignCharacterViewModelTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/484)
> PG-1166: Prevent narrator quote continuation chains

- Glyssen/Block.cs
- Glyssen/BlockMatchup.cs
- Glyssen/BookScript.cs
- Glyssen/Dialogs/AssignCharacterViewModel.cs
- Glyssen/PortionScript.cs
- Glyssen/Project.cs
- Glyssen/ProjectDataMigrator.cs
- Glyssen/ReferenceText.cs
- Glyssen/Resources/CharacterVerse.txt
- GlyssenTests/BlockMatchupTests.cs
- GlyssenTests/BookScriptTests.cs
- GlyssenTests/Dialogs/BlockNavigatorViewModelTests.cs
- GlyssenTests/ProjectDataMigratorTests.cs
- GlyssenTests/ProjectTests.cs
[WIP]: Added failing unit test to illustrate bug
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/482)
> PG-1168: Improved logic for re-applying user decisions to handle reference text alignments

- Glyssen/ProjectExporter.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/486)
> PG-1184: For Excel output, set right-to-left reading direction if needed

- Glyssen/Glyssen.csproj
- Glyssen/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/489)
> Upgraded to DesktopAnalytics 1.2.4.11

- Glyssen/App.config
- Glyssen/Project.cs
- Glyssen/Properties/Settings.Designer.cs
- Glyssen/Properties/Settings.settings
- Glyssen/UsxParser.cs
- GlyssenTests/UsxParserTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/490)
> PG-792: Improved USX parser to prevent verses with only punctuation

- Glyssen/Dialogs/ProjectSettingsDlg.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/493)
> PG-1189: Prevented msg about quote settings not matching when PT proj is unavailable

- DistFiles/localization/Glyssen.es.tmx
- Glyssen/App.config
- Glyssen/ApplicationMetadata.cs
- Glyssen/DataMigrator.cs
- Glyssen/Program.cs
- Glyssen/Project.cs
- Glyssen/Properties/Settings.Designer.cs
- Glyssen/Properties/Settings.settings
- GlyssenShared/Constants.cs
- GlyssenTests/ProjectTests.cs
This also includes a data migration to clean up the extra Sample project.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/494)
> PG-1192: Fixed problem: Audio was being appended twice for the default project name.

- Glyssen/BookScript.cs
- GlyssenTests/BookScriptTests.cs
WIP: Need unit tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/497)
> PG-1196: Fixed logic in GetIndexOfFirstBlockForVerse.

- Glyssen/BookScript.cs
- GlyssenTests/BookScriptTests.cs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/498)
> PG-1195: Fixed logic in GetIndexOfFirstBlockForVerse

- Glyssen/Dialogs/ExportToRecordingToolDlg.cs
- Glyssen/Dialogs/ViewScriptDlg.cs
- Glyssen/ProjectExporter.cs
- Glyssen/ScriptExporter.cs
- GlyssenTests/ProjectExportTests.cs
- GlyssenTests/ScriptExporterTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/499)
> PG-1193 Made Excel output columns consistent

- Glyssen/App.config
- Glyssen/Character/CharacterVerse.cs
- Glyssen/Properties/Settings.Designer.cs
- Glyssen/Properties/Settings.settings
- Glyssen/Quote/QuoteParser.cs
- Glyssen/Rules/CharacterGroupGenerator.cs
- GlyssenTests/BookScriptTests.cs
- GlyssenTests/Character/CharacterVerseDataTests.cs
- GlyssenTests/Quote/QuoteParserTests.cs
- GlyssenTests/ReferenceTextTests.cs
- GlyssenTests/Rules/CharacterGroupGeneratorTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/500)
> PG-1191: Changed IsExpected to treat Scripture Quotations as expected.

- Glyssen/Block.cs
There are a few I didn't do because I'm working on PG-1198 and those are going to change there. I thought it best to do these in a separate PR to avoid confusion.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/502)
> Refactoring to use expression-bodied properties in Block class

- Glyssen/Character/CharacterVerseData.cs
- GlyssenTests/Character/CharacterVerseDataTests.cs
Also improved/simplified implementation to avoid checking hundreds of non-existent verses.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/505)
> PG-1206: Added unit test to show the need for the code fix previously pushed

- Glyssen/Dialogs/UnappliedSplitsDlg.cs
- Glyssen/Dialogs/UnappliedSplitsViewModel.cs
- Glyssen/Glyssen.csproj
- Glyssen/MainForm.cs
- GlyssenTests/BookScriptTests.cs
- GlyssenTests/Dialogs/UnappliedSplitsViewModelTests.cs
- GlyssenTests/GlyssenTests.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/506)
> PG-1197: Break out split groups so each group has a correctly displayed reference

- Glyssen/ProjectExporter.cs
- Glyssen/ScriptExporter.cs
- GlyssenShared/Script/GlyssenScript.cs
- GlyssenTests/ScriptExporterTests.cs
- GlyssenTests/TestProject.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/507)
> PG-1210: Added delivery and paragraphStart attributes to glyssenscript

- Glyssen/Resources/CharacterDetail.txt
- Glyssen/Resources/CharacterVerse.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/508)
> Control file improvements

- Glyssen/BlockNavigator.cs
- GlyssenTests/Dialogs/AssignCharacterViewModelTests.cs
The caching was for performance reasons, but looking it up by index should be fast enough. If we wanted to keep caching it, we'd need to update the cached value to prevent holding onto an outdated block after applying a block matchup that results in the insertion of new blocks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/509)
> PG-1211: Removed cache of current block in navigator

- Glyssen/ProjectExporter.cs
- GlyssenTests/ProjectExportTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/512)
> PG-1193: Swapped order of reference text columns

- Glyssen/Glyssen.csproj
- Glyssen/Program.cs
- Glyssen/Utilities/AlertImpl.cs
- GlyssenTests/ProjectTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/514)
> PG-1227: Set implementation of Alert so Paratext load errors can be displayed

- Glyssen/ReferenceText.cs
#	Glyssen/ReferenceText.cs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/516)
> PG-794: Back out VERY BAD breaking change

- Glyssen/ReferenceText.cs
- GlyssenTests/ReferenceTextTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/517)
> PG-1133: Deal with indirect speech misalignments

- Glyssen/Dialogs/AssignCharacterDlg.cs
when right-clicking in rainbow grid pane
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/530)
> PG-1259: Check for row/column header to prevent out-of-range exception

- Glyssen.sln.DotSettings
- GlyssenTests/Dialogs/AssignCharacterViewModelTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/529)
> Test name typo cleanup

- Glyssen/Character/CharacterVerseData.cs
- Glyssen/Character/ControlCharacterVerseData.cs
- Glyssen/Resources/CharacterVerse.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/531)
> Added clarifying comment, delivery and Quotation line in LUK 1:58-59

- Glyssen/Resources/CharacterVerse.txt
This change was made previously in PG-1215 branch, but that is still in staging, and this is relevant now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/534)
> Added sea captain as option in REV 18:20

- Glyssen.sln.DotSettings
- Glyssen/Character/CharacterVerse.cs
- Glyssen/Project.cs
- Glyssen/ProjectDataMigrator.cs
- GlyssenTests/Dialogs/AssignCharacterViewModelTests.cs
- GlyssenTests/ProjectDataMigratorTests.cs
Handles conditions that would otherwise create inconsistencies and in some cases lead to unhandled exceptions.
Also added protective logic to AddProjectCharacterDetail to ensure that we are not adding detail records for characters already in the control file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/533)
> Added additional logic/steps to MigrateDeprecatedCharacterIds

- Glyssen/ReferenceText.cs
- GlyssenTests/ReferenceTextTests.cs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/536)
> PG-1264: Prevent negative index in MatchVernBlocksToReferenceTextBlocks

- GlyssenTests/ProjectTests.cs
- build/buildUpdate.sh
Increased timeout to prevent spurious failures when things are sluggish.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/537)
> Increased time allotted to long-running test. Made buildUpdate use https.

- Glyssen/Block.cs
- GlyssenTests/BlockTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/541)
> Merge PG-1274 from glyssen1.1

- Glyssen/Dialogs/VoiceActorAssignmentDlg.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/547)
> Changed tab to space in localization comment

- ControlDataIntegrityTests/NarratorOverridesTests.cs
- Glyssen/Character/ControlCharacterVerseData.cs
- Glyssen/Character/NarratorOverrides.cs
- GlyssenTests/BookScriptTests.cs
- GlyssenTests/Character/CharacterVerseDataTests.cs
- GlyssenTests/Character/NarratorOverridesTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/552)
> PG-1285 Fix crash in NarratorOverrides when versification change causes chapter change in startRef

- Glyssen/BookScript.cs
- Glyssen/ProjectDataMigrator.cs
- Glyssen/Resources/CharacterVerse.txt
- GlyssenTests/BookScriptTests.cs
- GlyssenTests/ProjectDataMigratorTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/557)
> PG-1286, PG-1291: Fixed reference text joining code to clone before joining

- Copy Libaries.bat
- Glyssen.sln
- Glyssen/Analysis/ProjectAnalysis.cs
- Glyssen/Controls/BlockProgressBar.cs
- Glyssen/Glyssen.csproj
- Glyssen/MainForm.cs
- Glyssen/Quote/QuoteParser.cs
- Glyssen/Quote/QuoteSystemGuesser.cs
- Glyssen/UsxParser.cs
- GlyssenEngine/GlyssenEngine.csproj
- GlyssenEngine/Utilities/MathUtilities.cs
- GlyssenEngineTest/GlyssenEngineTest.csproj
- GlyssenEngineTest/Utilities/MathUtilitiesTests.cs
- GlyssenTests/GlyssenTests.csproj
- Installer/Installer.wxs
Also moved MathUtilities from Glyssen to GlyssenEngine and MathUtilitiesTest from GlyssenTest to GlyssenEngineTest
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/559)
> Created the GlyssenEngine and GlyssenEngineTest projects

- Glyssen/ReferenceText.cs
- GlyssenTests/ReferenceTextTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/560)
> PG-1297: Prevent creation of a matchup that crosses a chapter boundary

- ControlDataIntegrityTests/App.config
- ControlDataIntegrityTests/ControlDataIntegrityTests.csproj
- ControlDataIntegrityTests/packages.config
- DevTools/App.config
- DevTools/DevTools.csproj
- DevTools/packages.config
- Glyssen/App.config
- Glyssen/Glyssen.csproj
- Glyssen/packages.config
- GlyssenTests/App.config
- GlyssenTests/GlyssenTests.csproj
- GlyssenTests/packages.config
- RefTextDevUtilities/RefTextDevUtilities.csproj
- RefTextDevUtilities/app.config
- RefTextDevUtilities/packages.config
- Reference Text Utility/App.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/565)
> Minor upgrade of PlatformAbstractions and Newtonsoft.Json

- Glyssen.sln
- GlyssenEngineTests/GlyssenEngineTests.csproj
- GlyssenEngineTests/Properties/AssemblyInfo.cs
- GlyssenEngineTests/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/567)
> Convert GlyssenEngineTests to .NetFramework

- GlyssenEngine/Character/CharacterVerseData.cs
- GlyssenEngineTests/Character/CharacterVerseDataTests.cs
Methods improved: IsCharacterOfType, IsCharacterStandard, IsCharacterExtraBiblical
Also removed a garbage comment in CharacterVerseDataTests, fixed a test name, and added a few additional test cases (that now pass because of improved implementation)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/578)
> Improved performance/accuracy in CharacterVerseData methods

- DistFiles/reference_texts/English/.guidsForInstaller.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/580)
> Updated .guidsForInstaller.xml with GUID for SNG.xml

- Glyssen/DataMigrator.cs
- Glyssen/Dialogs/WinFormsMessageBox.cs
- Glyssen/Glyssen.csproj
- Glyssen/Program.cs
- Glyssen/Project.cs
- Glyssen/Rules/CharacterGroupGenerator.cs
- GlyssenEngine/Utilities/MessageModal.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/584)
> Removed MessageBox from all code that will be moving to GlyssenEngine

- GlyssenEngine/Paratext/ParatextUsxBookList.cs
- GlyssenTests/ProjectTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/595)
> Added Default.Font and references so that Unit Testing would pass.

- Glyssen/Project.cs
- Glyssen/Quote/QuoteParser.cs
- Glyssen/UsxParser.cs
Crash caused by re-parsing existing books when a new book is included.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/598)
> PG-1312: Fix "Should not be parsing blocks that already have user-decisions applied"

- GlyssenTests/ProjectTests.cs
Also upped time-out for a test that had trouble on TeamCity.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/606)
> Added line to set Fonts.Default for ProjectTests.

- GlyssenTests/ProjectTests.cs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/607)
> Increased ProjectTests timeout values to avoid spurious timeouts on TC

- Glyssen/Controls/BlockProgressBar.cs
- Glyssen/Controls/ExistingProjectsList.cs
- Glyssen/Controls/SaveStatus.cs
- Glyssen/Controls/ScriptBlocksViewer.cs
- Glyssen/Controls/VoiceActorInformationGrid.cs
- Glyssen/Dialogs/AddCharacterToGroupDlg.cs
- Glyssen/Dialogs/AssignCharacterDlg.cs
- Glyssen/Dialogs/CastSizePlanningDlg.cs
- Glyssen/Dialogs/ExportDlg.cs
- Glyssen/Dialogs/ExportToRecordingToolDlg.cs
- Glyssen/Dialogs/GenerateGroupsProgressDialog.cs
- Glyssen/Dialogs/NarrationOptionsDlg.cs
- Glyssen/Dialogs/NewCharacterDlg.cs
- Glyssen/Dialogs/OpenProjectDlg.cs
- Glyssen/Dialogs/ProgressDialogWithAcknowledgement.cs
- Glyssen/Dialogs/ProjectSettingsDlg.cs
- Glyssen/Dialogs/QuotationMarksDlg.cs
- Glyssen/Dialogs/ScriptureRangeSelectionDlg.cs
- Glyssen/Dialogs/VoiceActorAssignmentDlg.cs
- Glyssen/Dialogs/VoiceActorInformationDlg.cs
- Glyssen/Program.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/609)
> Changed usages of Localizer to LocalizationManager in UI code

- GlyssenTests/Character/ControlCharacterVerseDataTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/612)
> Corrected name of test fixtures for ControlCharacterVerseData.

- Glyssen.sln.DotSettings
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/615)
> Added "Analytics" to shared spelling dictionary

- Glyssen/Character/ProjectCharacterVerseData.cs
- Glyssen/Dialogs/AssignCharacterDlg.cs
- Glyssen/Dialogs/AssignCharacterViewModel.cs
- Glyssen/Dialogs/ExportDlg.cs
- Glyssen/MainForm.cs
- Glyssen/Project.cs
- Glyssen/ProjectExporter.cs
- GlyssenTests/Dialogs/AssignCharacterViewModelTests.cs
"AddCharacter", "NarratorToQuote", "SetSingleVoice", "ProjectAnalysis"
Small amount of misc code cleanup and some changes to the scope of certain class members to prepare for Glyssen Engine moves.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/616)
> Moved several Analytics.Track calls into the UI layer:

- DistFiles/localization/Glyssen.es.tmx
- Glyssen/Dialogs/MoveCharactersToGroupUndoAction.cs
- Glyssen/Dialogs/VoiceActorAssignmentDlg.cs
- Glyssen/Dialogs/VoiceActorAssignmentViewModel.cs
- GlyssenTests/Dialogs/VoiceActorAssignmentViewModelTests.cs
Broke up logic to build data table to keep business logic in model but put data table stuff (which is UI-specific into the Dlg). Changed tests accordingly.
Fixed bug where a localizer ID was used for two different strings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/619)
> Moved some UI-oriented methods from VoiceActorAssignmentViewModel to dialog

- Glyssen/Dialogs/ExportToRecordingToolDlg.cs
- Glyssen/ScriptExporter.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/620)
> Minor refactoring to simplify signature of MakeGlyssenScriptFile

- Glyssen/ReferenceTextProxy.cs
- Glyssen/Rules/CharacterGroupsAdjuster.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/624)
> Misc code cleanup

- Glyssen/Dialogs/BlockNavigatorViewModel.cs
- Glyssen/Dialogs/QuotationMarksDlg.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/623)
> Refactoring to make BlockNavigatorViewModel handle updating BlockNavigator

- Glyssen/MainForm.cs
- Glyssen/Paratext/ParatextScrTextWrapper.cs
- Glyssen/Project.cs
Replaced UpdatePercentInitialized() with simple property.
Made some internal classes and methods public
Misc whitespace cleanup in Project.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/626)
> Moved non-UI part of exporting a glyssenshare file into project

- Glyssen/MainForm.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/629)
> PG-1323: Fixed crash due to missing parameter in call to String.Format

- Glyssen/BlockMatchup.cs
- Glyssen/Dialogs/BlockNavigatorViewModel.cs
- Glyssen/ProjectDataMigrator.cs
- GlyssenEngine/Resources/CharacterVerse.txt
- GlyssenTests/BlockMatchupTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/631)
> PG-1325: Fixed bug whereby an invalid block quote chain could be created

- Glyssen/Controls/ScriptBlocksGridView.cs
- Glyssen/Dialogs/AssignCharacterDlg.cs
- Glyssen/Dialogs/ProjectSettingsDlg.cs
- Glyssen/MainForm.cs
- Glyssen/Utilities/FontProxy.cs
- GlyssenEngine/ViewModels/AssignCharacterViewModel.cs
- GlyssenEngine/ViewModels/BlockNavigatorViewModel.cs
- GlyssenEngine/ViewModels/IFontInfo.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/634)
> Fix regression bugs

- Glyssen/Dialogs/AssignCharacterDlg.cs
- GlyssenEngine/ViewModels/AssignCharacterViewModel.cs
This is in code whose only purpose is to call Analytics.Track.
Also moved invocation of delegate until after the set is done and renamed from Setting to Set ("Setting" vaguely implies that maybe the delegate could cancel or deny the action, but that's not the point here.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/642)
> PG-1330: Added check for null before asking whether a character is narrator

- ControlDataIntegrityTests/CharacterVerseDataTests.cs
- GlyssenEngine/Resources/CharacterDetail.txt
- GlyssenEngine/Resources/CharacterVerse.txt
Added DataIntegrity test to disallow that combination in the CharacterVerse control file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/644)
> PG-1332: Replaced Narrator Hypothetical quotes with suitable alternatives

- GlyssenEngine/Project.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/646)
> PG-1335: Put in code to prevent crash when there are no included books

- GlyssenEngine/ProjectDataMigrator.cs
- GlyssenEngine/Quote/QuoteParser.cs
- GlyssenEngine/Resources/CharacterVerse.txt
- GlyssenEngine/Script/BookScript.cs
- GlyssenEngine/UsxParser.cs
- GlyssenEngineTests/ProjectDataMigratorTests.cs
- GlyssenEngineTests/Quote/QuoteParserTests.cs
- GlyssenEngineTests/Script/BookScriptTests.cs
Also fixed bug that caused IsParagraphStart to get set incorrectly when splitting a block to apply an Implicit character.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/649)
> PG-1334 Do not join verse text with section heads.

- .gitignore
- Glyssen/Program.cs
- Glyssen/Utilities/GeckoUtilities.cs
- GlyssenTests/Controls/BrowserTests.cs
- GlyssenTests/GlyssenTests.csproj
- GlyssenTests/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/651)
> Fixed up plumbing issues so BrowserTests could be run

- ControlDataIntegrityTests/ControlDataIntegrityTests.csproj
- ControlDataIntegrityTests/packages.config
- DevTools/DevTools.csproj
- DevTools/packages.config
- DistFiles/aboutBox.htm
- Glyssen/Glyssen.csproj
- Glyssen/Properties/AssemblyInfo.cs
- Glyssen/packages.config
- GlyssenEngine/GlyssenEngine.csproj
- GlyssenEngineTests/GlyssenEngineTests.csproj
- GlyssenEngineTests/Properties/AssemblyInfo.cs
- GlyssenEngineTests/packages.config
- GlyssenShared/GlyssenShared.csproj
- GlyssenSharedTests/GlyssenSharedTests.csproj
- GlyssenSharedTests/packages.config
- GlyssenTests/GlyssenTests.csproj
- GlyssenTests/packages.config
- RefTextDevUtilities/RefTextDevUtilities.csproj
- RefTextDevUtilities/packages.config
- Reference Text Utility/Reference Text Utility.csproj
- Reference Text Utility/packages.config
(This is the latest beta.)
Bumped up other packages to consolidate on single version
Bumped up copyright year to 2020
Bumped up to latest version of L10nSharp.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/653)
> Bumped up SIL.Windows.Forms to get registered trademark version of SIL logo

- GlyssenEngine/GlyssenEngine.csproj
- GlyssenShared/GlyssenShared.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/657)
> Use GitVersion 5.1.2

- Glyssen/Controls/VoiceActorInformationGrid.cs
- Glyssen/Dialogs/AssignCharacterDlg.cs
- Glyssen/Dialogs/VoiceActorAssignmentDlg.cs
- GlyssenEngine/ViewModels/VoiceActorInformationViewModel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/656)
> PG-1340: Ensure RemoveActor entry is always added to the drop-down even if there are no actors

- GlyssenEngine/Script/BlockMatchup.cs
- GlyssenEngine/Script/BookScript.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/663)
> PG-1347/PG-1349: Prevent exception when reapplying matchups

- build/Glyssen.proj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/664)
> Removed “Upload” target (publishing now done via SSH Upload on TC)

- Installer/template.download_info
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/668)
> PG-1345: Fixed type in download_info template

- build/Glyssen.proj
- build/TestInstallerBuild.bat
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/670)
> PG-1356: Added steps to sign the engine

- DistFiles/ReleaseNotes.md
Better late than never!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/672)
> Added release note about "he said" feature

- GlyssenEngine/Resources/CharacterDetail.txt
- GlyssenEngine/Resources/CharacterVerse.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/673)
> Added potential speakers in Acts

- Glyssen/MainForm.cs
- GlyssenEngine/Project.cs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/676)
> PG-1367: Corrected error-handling in quote parser and project loading

- Glyssen/MainForm.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/677)
> PG-1371: Enabled export menu

- Glyssen/Dialogs/AssignCharacterDlg.cs
- GlyssenEngine/Script/Block.cs
- GlyssenEngine/Script/BlockMatchup.cs
- GlyssenEngine/ViewModels/AssignCharacterViewModel.cs
- GlyssenEngineTests/ViewModelTests/AssignCharacterViewModelTests.cs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/679)
> PG-957: Up/Down & Split Text commands can't move text into Section Heads

- Glyssen/Glyssen.csproj
- GlyssenTests/GlyssenTests.csproj
- Reference Text Utility/Reference Text Utility.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/681)
> Added references back in to *Sharp DLLs to eliminate build warnings

- ControlDataIntegrityTests/ControlDataIntegrityTests.csproj
- Glyssen/Glyssen.csproj
- GlyssenEngine/GlyssenEngine.csproj
- GlyssenEngineTests/GlyssenEngineTests.csproj
- GlyssenFileBasedPersistence/GlyssenFileBasedPersistence.csproj
- GlyssenShared/GlyssenShared.csproj
- GlyssenSharedTests/GlyssenSharedTests.csproj
- GlyssenTests/GlyssenTests.csproj
- InMemoryTestPersistence/InMemoryTestPersistence.csproj
- RefTextDevUtilities/RefTextDevUtilities.csproj
- Reference Text Utility/Reference Text Utility.csproj
- build/Glyssen.proj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/680)
> Added properties for packaging GlyssenEngine/GlyssenShared for nuget deployment

- DistFiles/reference_texts/English/1CO.xml
- DistFiles/reference_texts/English/HEB.xml
- DistFiles/reference_texts/English/MRK.xml
- DistFiles/reference_texts/English/english.glyssen
- Glyssen/Dialogs/ProjectSettingsDlg.Designer.cs
- Glyssen/Dialogs/ProjectSettingsDlg.cs
- Glyssen/Dialogs/ProjectSettingsDlg.resx
- GlyssenEngine/ReferenceText.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/682)
> PG-1376: Added OT/NT version info to English reference text metadata and UI to display it.

- Glyssen/Dialogs/ProjectSettingsDlg.Designer.cs
- Glyssen/Dialogs/ProjectSettingsDlg.cs
- Glyssen/Dialogs/ProjectSettingsDlg.resx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/683)
> PG-1337: Added warning when reference text does not cover all books in the project

- CHANGELOG.md
- GitVersion.yml
- Glyssen.sln.DotSettings
- Glyssen/MainForm.cs
- Glyssen/Program.cs
- GlyssenEngine/GitVersion.yml
- GlyssenShared/GitVersion.yml
when passing it to L10nSharp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/686)
> Stripped off non-numeric portion of version number to prevent crash

- Glyssen/Controls/ExistingProjectsList.cs
- GlyssenEngine/Project.cs
- GlyssenFileBasedPersistence/ProjectRepository.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/691)
> PG-1380: Solved bugs related to making projects inactive

- Glyssen/Controls/ScriptBlocksGridView.cs
- GlyssenEngine/Resources/CharacterVerse.txt
Some manuscripts do not contain the part of the text that has this Scripture quote. (I intentionally did not bump up the C-V version number since this is a minor change that will not affect parsing, just the filter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/693)
> PG-1295: Changed Quotation to Potential for MAT 27:35

- GlyssenEngine/ReferenceText.cs
- GlyssenEngineTests/ReferenceTextTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/696)
> PG-1374: Made Reference text matching logic fully account for versification differences.

- ControlDataIntegrityTests/App.config
- ControlDataIntegrityTests/ControlDataIntegrityTests.csproj
- ControlDataIntegrityTests/packages.config
- DevTools/App.config
- DevTools/DevTools.csproj
- DevTools/packages.config
- Glyssen/Glyssen.csproj
- GlyssenEngine/GlyssenEngine.csproj
- GlyssenEngineTests/GlyssenEngineTests.csproj
- GlyssenEngineTests/app.config
- GlyssenEngineTests/packages.config
- GlyssenFileBasedPersistence/GlyssenFileBasedPersistence.csproj
- GlyssenShared/GlyssenShared.csproj
- GlyssenSharedTests/GlyssenSharedTests.csproj
- GlyssenSharedTests/app.config
- GlyssenSharedTests/packages.config
- GlyssenTests/App.config
- GlyssenTests/GlyssenTests.csproj
- GlyssenTests/packages.config
- RefTextDevUtilities/RefTextDevUtilities.csproj
- RefTextDevUtilities/app.config
- RefTextDevUtilities/packages.config
- Reference Text Utility/App.config
- Reference Text Utility/Reference Text Utility.csproj
- Reference Text Utility/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/697)
> Upgraded ParatextData to 9.1.7-beta and all of the SIL DLLs to 8.0.0-beta0153

- GlyssenEngine/ReferenceText.cs
- GlyssenEngineTests/ReferenceTextTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/698)
> PG-1374: Added new test to prove that previous fix works even in Psalms.

- GlyssenShared/Bundle/GlyssenDblTextMetadataBase.cs
See https://github.com/dotnet/runtime/issues/38025
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/699)
> Work-around to a bug in .net Core XmlSerializer

- GlyssenEngine/Resources/CharacterVerse.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/702)
> PG-1383: Added/tweaked C-V entries for ISA 41

- GlyssenEngine/GlyssenEngine.csproj
- GlyssenEngine/GlyssenEngine.targets
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/703)
> Added reference text and usfm.sty files to GlyssenEngine nuget package

- CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/705)
> Updated CHANGELOG.md with info about added files in GlyssenEngine package

- Glyssen/Dialogs/ProjectSettingsDlg.cs
- Glyssen/Dialogs/QuotationMarksDlg.cs
- GlyssenEngine/Project.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/706)
> PG-1391: In HandleQuoteSystemChanged, do not check for changes in available books before re-parsing

- Glyssen/Program.cs
- Installer/Installer.wxs
- build/TestInstallerBuild.bat
Also used more meaningful InstallScope attribute instead of ALLUSERS=1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/708)
> PG-1387: Changed custom action that launches Glyssen to impersonate the (non-elevated) user

- GlyssenEngine/ReferenceText.cs
- GlyssenEngine/Script/Block.cs
- GlyssenEngine/Script/BlockMatchup.cs
- GlyssenEngineTests/ProjectTests.cs
- GlyssenEngineTests/ReferenceTextTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/710)
> PG-1394: Improved logic for applying reporting clauses when matching blocks

- GlyssenEngine/ReferenceText.cs
- GlyssenEngine/Resources/CharacterDetail.txt
- GlyssenEngine/Resources/CharacterVerse.txt
- GlyssenEngineTests/ReferenceTextTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/711)
> PG-1393: Prevent aligning two adjacent blocks in a verse bridge to the same ref combined ref block

- GlyssenEngine/ReferenceText.cs
- GlyssenEngineTests/ReferenceTextTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/712)
> PG-1395: Fixed - alignment of he-said block caused omission of reference text block

- GlyssenEngine/Export/ProjectExporter.cs
- GlyssenEngineTests/Export/ProjectExporterTests.cs
- GlyssenShared/BlockElement.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/713)
> PG-1399: Added missing 1-minute pause annotation at the end of REV

- build/Glyssen.proj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/719)
> Fixed incorrect comment in Glyssen.proj

- DistFiles/reference_texts/English/1CH.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/721)
> Fixed incorrect quotation mark levels in 1CH 17:4-14

- GlyssenEngine/ReferenceText.cs
- GlyssenEngineTests/ReferenceTextTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/725)
> PG-1403: Prevented change to Reference Text as a side-effect of TryMatchToReportingClause

- DistFiles/reference_texts/English/.guidsForInstaller.xml
- Installer/Bootstrapper/Glyssen Bootstrap Installer.wxs
- Installer/Installer.wxs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/730)
> PG-1414 Changed to launch Glyssen from bootstrapper so it would not use elevated privileges

- GlyssenEngine/Resources/CharacterVerse.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/731)
> Added possible (rare) quote for John the Baptist in MAT 3:15

- GlyssenEngine/Resources/CharacterDetail.txt
- GlyssenEngine/Resources/CharacterVerse.txt
PG-163: Changed Normal to Implicit for some of Jesus' lines in JHN 6. This improves ability to correctly parse in the absence of correct quotation markup.
PG-1110: Added some rare/indirect speakers
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/736)
> PG-163/PG-1110: Improvements to control files

- DistFiles/reference_texts/English/english.glyssen
- DistFiles/reference_texts/Russian/russian.glyssen
- GlyssenEngine/ReferenceText.cs
- GlyssenShared/Constants.cs
- RefTextDevUtilities/ReferenceTextUtility.cs
- Reference Text Utility/RefTextUtilityForm.Designer.cs
- Reference Text Utility/RefTextUtilityForm.cs
Also fixed PG-1418: crash (and got rid of one of the uses of deprecated BackgroundWorker) caused by trying to load a different file before the one being loaded finishes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/735)
> PG-1416: Enhanced Reference Text Utility to be able to specify the DG version

- ControlDataIntegrityTests/App.config
- ControlDataIntegrityTests/ControlDataIntegrityTests.csproj
- ControlDataIntegrityTests/packages.config
- DevTools/App.config
- DevTools/DevTools.csproj
- DevTools/packages.config
- Glyssen/Dialogs/ProjectSettingsDlg.Designer.cs
- Glyssen/Dialogs/ProjectSettingsDlg.cs
- Glyssen/Dialogs/ProjectSettingsDlg.resx
- Glyssen/Glyssen.csproj
- GlyssenEngine/GlyssenEngine.csproj
- GlyssenEngine/Utilities/StringExtensions.cs
- GlyssenEngine/ViewModels/AssignCharacterViewModel.cs
- GlyssenEngineTests/GlyssenEngineTests.csproj
- GlyssenEngineTests/app.config
- GlyssenEngineTests/packages.config
- GlyssenFileBasedPersistence/GlyssenFileBasedPersistence.csproj
- GlyssenShared/GlyssenShared.csproj
- GlyssenSharedTests/GlyssenSharedTests.csproj
- GlyssenSharedTests/app.config
- GlyssenSharedTests/packages.config
- GlyssenTests/App.config
- GlyssenTests/GlyssenTests.csproj
- GlyssenTests/packages.config
- RefTextDevUtilities/RefTextDevUtilities.csproj
- RefTextDevUtilities/app.config
- RefTextDevUtilities/packages.config
- Reference Text Utility/App.config
- Reference Text Utility/Reference Text Utility.csproj
- Reference Text Utility/packages.config
This prevents later using it to create an illegal path.
Also did some code cleanup in ProjectSettingsDlg.
Note: this is a WIP because it's waiting on https://github.com/sillsdev/libpalaso/pull/983 (after which I'll need to bump up to the latest beta version of that libpalaso DLL).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/734)
> PG-1412: Added validation for Audio Stock Number

- DistFiles/reference_texts/English/ACT.xml
- DistFiles/reference_texts/English/HEB.xml
- DistFiles/reference_texts/English/JAS.xml
- DistFiles/reference_texts/English/JHN.xml
- DistFiles/reference_texts/English/LUK.xml
- DistFiles/reference_texts/English/MAT.xml
- DistFiles/reference_texts/English/MRK.xml
- DistFiles/reference_texts/English/english.glyssen
- DistFiles/reference_texts/Russian/1CO.xml
- DistFiles/reference_texts/Russian/ACT.xml
- DistFiles/reference_texts/Russian/HEB.xml
- DistFiles/reference_texts/Russian/JAS.xml
- DistFiles/reference_texts/Russian/JHN.xml
- DistFiles/reference_texts/Russian/LUK.xml
- DistFiles/reference_texts/Russian/MAT.xml
- DistFiles/reference_texts/Russian/MRK.xml
- DistFiles/reference_texts/Russian/REV.xml
- DistFiles/reference_texts/Russian/ROM.xml
- GlyssenSharedTests/Resources/FrenchMRKRefText.xml
- RefTextDevUtilities/ReferenceTextUtility.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/738)
> Reference text improvements from Director's Guide version 106

- ControlDataIntegrityTests/CharacterVerseDataTests.cs
- Glyssen.sln.DotSettings
- GlyssenEngine/Character/ControlCharacterVerseData.cs
- GlyssenEngine/Resources/CharacterDetail.txt
- GlyssenEngine/Resources/CharacterVerse.txt
- GlyssenEngineTests/Character/ControlCharacterVerseDataTests.cs
- GlyssenEngineTests/Resources/TestCharacterVerseOct2015.txt
PG-793: Ensured that all Quotations in the control file have an alternative to being dramatized as quotations.
PG-1424: Prevented rare Scripture quotes from being treated as expected.
Added a few (mostly obscure) speakers/alternates and some Needs Review entries
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/739)
> PG-793 & PG-1424: Improvements to control files and Expected Quotes

- GlyssenEngine/Resources/CharacterVerse.txt
based on Damal project (ee PG-1326)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/741)
> Added some rare character speaking parts

- GlyssenEngine/Resources/CharacterVerse.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/747)
> Changed several places from Normal to implicit in C/V control file

- GlyssenEngine/ViewModels/AssignCharacterViewModel.cs
- GlyssenEngine/ViewModels/BlockNavigatorViewModel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/742)
> PG-1426: Prevent SetBlock form attempting to set a section head as an anchor block

- build/Glyssen.proj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/753)
> Removed useNUnit-x86 properties, which are no longer needed.

- GlyssenEngineTests/TestProject.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/759)
> Use test context instead of random number

- GlyssenEngine/Resources/CharacterVerse.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/761)
> Tweak to make a CV entry Potential for verse not contained in some manuscripts

- appveyor.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/760)
> Add AppVeyor config file

- DistFiles/reference_texts/Russian/ACT.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/764)
> Replaced errant Thai script in Russian DG.

- GlyssenEngine/ReferenceText.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/766)
> PG-1434: Prevent crash when last chapter has no Scripture blocks

- DistFiles/aboutBox.htm
- GlyssenEngine/GlyssenEngine.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/767)
> Updated copyright year and added acknowledgment to aboutBox.htm

- Glyssen/Dialogs/ScriptureRangeSelectionDlg.cs
- GlyssenEngine/Project.cs
- GlyssenEngine/ProjectBase.cs
- GlyssenEngine/UsxParser.cs
- GlyssenEngineTests/UsxParserTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/769)
> PG-1434 [WIP]: In UsxParser, prevent non-scripture blocks at end of book

- ControlDataIntegrityTests/App.config
- ControlDataIntegrityTests/ControlDataIntegrityTests.csproj
- ControlDataIntegrityTests/packages.config
- DevTools/App.config
- DevTools/DevTools.csproj
- DevTools/packages.config
- Glyssen/Glyssen.csproj
- GlyssenEngine/GlyssenEngine.csproj
- GlyssenEngineTests/GlyssenEngineTests.csproj
- GlyssenEngineTests/app.config
- GlyssenEngineTests/packages.config
- GlyssenFileBasedPersistence/GlyssenFileBasedPersistence.csproj
- GlyssenFileBasedPersistenceTests/GlyssenFileBasedPersistenceTests.csproj
- GlyssenShared/GlyssenShared.csproj
- GlyssenSharedTests/GlyssenSharedTests.csproj
- GlyssenSharedTests/app.config
- GlyssenSharedTests/packages.config
- GlyssenTests/App.config
- GlyssenTests/GlyssenTests.csproj
- GlyssenTests/packages.config
- RefTextDevUtilities/RefTextDevUtilities.csproj
- RefTextDevUtilities/app.config
- RefTextDevUtilities/packages.config
- Reference Text Utility/App.config
- Reference Text Utility/Reference Text Utility.csproj
- Reference Text Utility/packages.config
- l10n/l10n.proj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/770)
> Updated to latest stable version of all SIL, System and Microsoft packages

- GlyssenEngine/Project.cs
- GlyssenEngine/Quote/QuoteParser.cs
- GlyssenEngineTests/Quote/QuoteParserTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/771)
> PG-1442: Fixed failure to account for pending verse number or punctuation text from previous block

- ControlDataIntegrityTests/App.config
- ControlDataIntegrityTests/ControlDataIntegrityTests.csproj
- ControlDataIntegrityTests/packages.config
- DevTools/App.config
- DevTools/DevTools.csproj
- DevTools/packages.config
- DistFiles/aboutBox.htm
- Glyssen/App.config
- Glyssen/Glyssen.csproj
- GlyssenEngine/Paratext/ParatextScrTextWrapper.cs
- GlyssenEngineTests/GlyssenEngineTests.csproj
- GlyssenEngineTests/app.config
- GlyssenEngineTests/packages.config
- GlyssenFileBasedPersistenceTests/GlyssenFileBasedPersistenceTests.csproj
- GlyssenSharedTests/GlyssenSharedTests.csproj
- GlyssenSharedTests/app.config
- GlyssenSharedTests/packages.config
- GlyssenTests/App.config
- GlyssenTests/GlyssenTests.csproj
- GlyssenTests/packages.config
- Installer/Installer.wxs
- RefTextDevUtilities/RefTextDevUtilities.csproj
- RefTextDevUtilities/app.config
- RefTextDevUtilities/packages.config
- Reference Text Utility/App.config
- Reference Text Utility/Reference Text Utility.csproj
- Reference Text Utility/packages.config
- build/Glyssen.proj
Bumped up to newer versions of some DLLs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/772)
> Added Makdig.Signed to installer

- GlyssenEngine/ReferenceText.cs
- GlyssenEngineTests/ReferenceTextTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/765)
> PG-1433: Split/align multi-verse ref block to match multi-block vernacular quote

- GlyssenEngine/Quote/QuoteParser.cs
- GlyssenEngineTests/Quote/QuoteParserTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/777)
> PG-1435: Prevent crash setting up QuoteParser when no quotation marks are specified

- GlyssenEngine/Resources/CharacterVerse.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/778)
> PG-1440: Added officers as a Rare entry for ACT 5:22

- DistFiles/reference_texts/English/1CO.xml
- DistFiles/reference_texts/English/english.glyssen
- DistFiles/reference_texts/Russian/1CO.xml
- DistFiles/reference_texts/Russian/ACT.xml
- DistFiles/reference_texts/Russian/JHN.xml
- DistFiles/reference_texts/Russian/LUK.xml
- DistFiles/reference_texts/Russian/MRK.xml
- DistFiles/reference_texts/Russian/russian.glyssen
- GlyssenEngine/Resources/Annotations.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/779)
> Upgraded to v. 107 of the FCBH DG

- GlyssenEngine/ReferenceText.cs
- GlyssenEngineTests/ReferenceTextTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/782)
> PG-1459: Fixed logic error in CombineRefBlocksToCreateMatch.

- RefTextDevUtilities/ReferenceTextUtility.cs
- Reference Text Utility/RefTextUtilityForm.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/783)
> Prevent crash and set metadata when processing new language with the ReferenceTextUtility

- RefTextDevUtilities/ReferenceTextUtility.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/785)
> Fixed bug to prevent NullReferenceException in ReferenceTextUtility

- CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/791)
> Updated CHANGELOG.md with information about OT reference text

- Installer/Installer.wxs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/793)
> PG-1469: Added DLLs to Installer required for Markdig.Signed.dll

- Glyssen/Dialogs/ProjectSettingsDlg.Designer.cs
- Glyssen/Dialogs/ProjectSettingsDlg.cs
- Glyssen/Dialogs/QuotationMarksDlg.cs
- Glyssen/MainForm.cs
- GlyssenEngine/Utilities/MathUtilities.cs
- GlyssenEngineTests/Utilities/MathUtilitiesTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/794)
> PG-1470: More elegantly handle cases where project contains no usable/included books.

- DistFiles/reference_texts/English/1CO.xml
- DistFiles/reference_texts/English/JHN.xml
- DistFiles/reference_texts/English/LUK.xml
- DistFiles/reference_texts/English/MAT.xml
- DistFiles/reference_texts/English/MRK.xml
- DistFiles/reference_texts/English/ROM.xml
- DistFiles/reference_texts/English/english.glyssen
- DistFiles/reference_texts/Russian/1CO.xml
- DistFiles/reference_texts/Russian/JHN.xml
- DistFiles/reference_texts/Russian/LUK.xml
- DistFiles/reference_texts/Russian/MAT.xml
- DistFiles/reference_texts/Russian/MRK.xml
- DistFiles/reference_texts/Russian/ROM.xml
- DistFiles/reference_texts/Russian/russian.glyssen
- GlyssenEngine/Resources/CharacterVerse.txt
- GlyssenEngineTests/ReferenceTextTests.cs
- RefTextDevUtilities/ReferenceTextUtility.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/795)
> Updated the English and Russian reference texts to DG v. 112

- DistFiles/ReleaseNotes.md
- GlyssenEngine/Export/ProjectExporter.cs
- GlyssenEngineTests/Export/ProjectExporterTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/810)
> PG-1478: Make block numbers in actor- and book-specific exports match the numbers in the master file

- Glyssen.sln.DotSettings
- Glyssen/Controls/ExistingProjectsList.cs
- Glyssen/Dialogs/OpenProjectDlg.cs
- GlyssenEngine/Paratext/ParatextProjectProxy.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/811)
> PG-1479: Omit Paratext projects from list if an exception is thrown creating proxy

- DistFiles/ReleaseNotes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/819)
> Corrected date and version # in ReleaseNotes

- Glyssen/Dialogs/AssignCharacterDlg.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/820)
> Corrected flaw in the to determine whether to send an analytics tracking event

- GlyssenEngine/Resources/CharacterVerse.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/822)
> Corrected punctuation error in alias in CV control file

- ControlDataIntegrityTests/App.config
- ControlDataIntegrityTests/ControlDataIntegrityTests.csproj
- ControlDataIntegrityTests/packages.config
- DevTools/App.config
- DevTools/DevTools.csproj
- DevTools/packages.config
- Glyssen/App.config
- Glyssen/Glyssen.csproj
- GlyssenEngine/GlyssenEngine.csproj
- GlyssenEngineTests/GlyssenEngineTests.csproj
- GlyssenEngineTests/app.config
- GlyssenEngineTests/packages.config
- GlyssenSharedTests/GlyssenSharedTests.csproj
- GlyssenSharedTests/app.config
- GlyssenSharedTests/packages.config
- GlyssenTests/App.config
- GlyssenTests/GlyssenTests.csproj
- GlyssenTests/packages.config
- RefTextDevUtilities/RefTextDevUtilities.csproj
- RefTextDevUtilities/app.config
- Reference Text Utility/App.config
- Reference Text Utility/Reference Text Utility.csproj
Also cleaned up some spurious cruft in a couple csproj files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/832)
> Bumped Newtonsoft.Json to version 13.

- ControlDataIntegrityTests/App.config
- ControlDataIntegrityTests/ControlDataIntegrityTests.csproj
- ControlDataIntegrityTests/packages.config
- DevTools/App.config
- DevTools/DevTools.csproj
- DevTools/packages.config
- Glyssen/Glyssen.csproj
- GlyssenEngine/GlyssenEngine.csproj
- GlyssenEngine/UsxParser.cs
- GlyssenEngineTests/GlyssenEngineTests.csproj
- GlyssenEngineTests/app.config
- GlyssenEngineTests/packages.config
- GlyssenFileBasedPersistence/GlyssenFileBasedPersistence.csproj
- GlyssenShared/GlyssenShared.csproj
- GlyssenSharedTests/GlyssenSharedTests.csproj
- GlyssenSharedTests/app.config
- GlyssenSharedTests/packages.config
- GlyssenTests/App.config
- GlyssenTests/GlyssenTests.csproj
- GlyssenTests/packages.config
- RefTextDevUtilities/RefTextDevUtilities.csproj
- Reference Text Utility/Reference Text Utility.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/835)
> PG-1487: Support for DBL metadata version 2.2.1 and USX 3.0

- ControlDataIntegrityTests/CharacterVerseDataTests.cs
- GlyssenEngine/Resources/CharacterDetail.txt
- GlyssenEngine/Resources/CharacterVerse.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/836)
> Added several rare speaking characters (mostly in the OT)

- Installer/template.releasenotes.download_info
- build/Glyssen.proj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/837)
> Added info about release notes so they can be published on website

- Glyssen.sln.DotSettings
- Glyssen/Dialogs/ExportToRecordingToolDlg.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/839)
> Added analytics event for glyssenscript exports

- CHANGELOG.md
- ControlDataIntegrityTests/App.config
- ControlDataIntegrityTests/ControlDataIntegrityTests.csproj
- ControlDataIntegrityTests/packages.config
- DevTools/App.config
- DevTools/DevTools.csproj
- DevTools/packages.config
- Glyssen/Glyssen.csproj
- GlyssenCharacters/GlyssenCharacters.csproj
- GlyssenEngine/GlyssenEngine.csproj
- GlyssenEngineTests/GlyssenEngineTests.csproj
- GlyssenEngineTests/app.config
- GlyssenEngineTests/packages.config
- GlyssenFileBasedPersistence/GlyssenFileBasedPersistence.csproj
- GlyssenShared/GlyssenShared.csproj
- GlyssenSharedTests/GlyssenSharedTests.csproj
- GlyssenSharedTests/app.config
- GlyssenSharedTests/packages.config
- GlyssenTests/App.config
- GlyssenTests/GlyssenTests.csproj
- GlyssenTests/packages.config
- RefTextDevUtilities/RefTextDevUtilities.csproj
- Reference Text Utility/Reference Text Utility.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/840)
> Update dependencies - security fix

- Glyssen/Dialogs/ExportDlg.Designer.cs
- Glyssen/Dialogs/ExportDlg.cs
- GlyssenEngine/Export/ProjectExporter.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/841)
> Added export option to break out chapters into separate sheets

- CHANGELOG.md
- DistFiles/ReleaseNotes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/glyssen/842)
> Added information about version 5.0 to CHANGELOG and ReleaseNotes

- GlyssenCharacters/Resources/CharacterVerse.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/Glyssen/847)
> PTX-22878: Added CV entries to accommodate different ways of doing quotes in REV 22

- ControlDataIntegrityTests/App.config
- ControlDataIntegrityTests/ControlDataIntegrityTests.csproj
- ControlDataIntegrityTests/packages.config
- DevTools/App.config
- DevTools/DevTools.csproj
- DevTools/packages.config
- Glyssen/Glyssen.csproj
- GlyssenCharacters/GlyssenCharacters.csproj
- GlyssenCharacters/Resources/CharacterDetail.txt
- GlyssenCharacters/Resources/CharacterVerse.txt
- GlyssenCharactersTests/GlyssenCharactersTests.csproj
- GlyssenEngine/GlyssenEngine.csproj
- GlyssenEngineTests/GlyssenEngineTests.csproj
- GlyssenEngineTests/app.config
- GlyssenEngineTests/packages.config
- GlyssenFileBasedPersistence/GlyssenFileBasedPersistence.csproj
- GlyssenFileBasedPersistenceTests/GlyssenFileBasedPersistenceTests.csproj
- GlyssenShared/GlyssenShared.csproj
- GlyssenSharedTests/GlyssenSharedTests.csproj
- GlyssenSharedTests/app.config
- GlyssenSharedTests/packages.config
- GlyssenTests/App.config
- GlyssenTests/GlyssenTests.csproj
- GlyssenTests/packages.config
- RefTextDevUtilities/RefTextDevUtilities.csproj
- Reference Text Utility/Reference Text Utility.csproj
- build/Glyssen.proj
Upgraded dependencies
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/Glyssen/849)
> PTX-23266: Added a few more rare/potential quote instances to control files

- GlyssenCharacters/Resources/CharacterVerse.txt
based on observations of what is common in many translations
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/Glyssen/850)
> PTX-22878: Changed a bunch of "Normal" quotes to be indirect or Potential

- Glyssen/Glyssen.csproj
- GlyssenCharacters/GlyssenCharacters.csproj
- GlyssenCharactersTests/GlyssenCharactersTests.csproj
- GlyssenFileBasedPersistence/GlyssenFileBasedPersistence.csproj
- GlyssenFileBasedPersistenceTests/app.config
- GlyssenShared/GlyssenShared.csproj
- GlyssenTests/GlyssenTests.csproj
- GlyssenTests/packages.config
- Installer/template.releasenotes.download_info
- RefTextDevUtilities/app.config
- Reference Text Utility/App.config
- Reference Text Utility/Reference Text Utility.csproj
- build/Glyssen.proj
- build/TestBuild.bat
- build/TestInstallerBuild.bat
- build/TestRTUInstallerBuild.bat
Also added Platform property to build file.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/Glyssen/866)
> Added build target to convert release notes to HTML

- ControlDataIntegrityTests/App.config
- ControlDataIntegrityTests/ControlDataIntegrityTests.csproj
- ControlDataIntegrityTests/packages.config
- DevTools/App.config
- DevTools/DevTools.csproj
- DevTools/packages.config
- Glyssen/Glyssen.csproj
- GlyssenCharacters/GlyssenCharacters.csproj
- GlyssenCharactersTests/GlyssenCharactersTests.csproj
- GlyssenEngine/GlyssenEngine.csproj
- GlyssenEngineTests/GlyssenEngineTests.csproj
- GlyssenEngineTests/app.config
- GlyssenEngineTests/packages.config
- GlyssenFileBasedPersistence/GlyssenFileBasedPersistence.csproj
- GlyssenShared/GlyssenShared.csproj
- GlyssenSharedTests/GlyssenSharedTests.csproj
- GlyssenSharedTests/app.config
- GlyssenSharedTests/packages.config
- GlyssenTests/App.config
- GlyssenTests/GlyssenTests.csproj
- GlyssenTests/packages.config
- RefTextDevUtilities/RefTextDevUtilities.csproj
- Reference Text Utility/Reference Text Utility.csproj
This includes some security updates that dependabot wanted to do
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/Glyssen/867)
> Upgraded dependencies (minor version)

- ControlDataIntegrityTests/packages.config
- DevTools/packages.config
- DistFiles/aboutBox.htm
- Glyssen/Glyssen.csproj
- GlyssenEngineTests/packages.config
- GlyssenTests/App.config
- GlyssenTests/GlyssenTests.csproj
- GlyssenTests/packages.config
- Installer/Installer.wxs
- Reference Text Utility/Reference Text Utility.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/Glyssen/870)
> Updated dependencies. Most notably, DesktopAnalytics

- .gitignore
- ControlDataIntegrityTests/ControlDataIntegrityTests.csproj
- ControlDataIntegrityTests/packages.config
- DevTools/DevTools.csproj
- DevTools/packages.config
- Glyssen/MainForm.cs
Also updated some DLLs that dependabot wanted updated.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/Glyssen/874)
> PG-1398: keep share menu enabled

- .gitignore
- Installer/Installer.wxs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/Glyssen/882)
> Added missing files to Installer needed for Analytics

- Glyssen/Controls/AutoScrollGrid.cs
- Glyssen/Controls/DataGridViewListBox.cs
- Glyssen/Controls/DataGridViewMultiColumnComboBoxCell.cs
- Glyssen/Controls/DataGridViewMultiColumnComboBoxColumn.cs
- Glyssen/Controls/DataGridViewMultiColumnComboBoxEditingControl.cs
- Glyssen/Controls/VoiceActorInformationGrid.cs
- Glyssen/Dialogs/ProjectSettingsDlg.cs
- Glyssen/Dialogs/YesNoApplyToAllDlg.cs
- Glyssen/Program.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/Glyssen/887)
> Changed http: in code and comments to https: as appropriate

- DistFiles/aboutBox.htm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/Glyssen/892)
> Fixed misplaced slash in img element in aboutBox.htm
